#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
지은·인준 캐릭터 베이스/포즈 레퍼런스 사진을 Supabase에 저장 (정식·재현용).

- 자격증명: 전부 .env 에서 로드 (소스에 하드코딩 금지)
- characters / character_assets 테이블 upsert (psycopg2, ON CONFLICT)
- character-base 스토리지 버킷에 PNG 업로드 (supabase client, service_role 키)
- 멱등: 몇 번을 다시 돌려도 안전 (upsert + remove→upload)

사용법:
    python supabase/save_characters.py

cf. 제작 방법은 CHARACTER_ASSET_METHOD.md, 매니페스트는 home_vocab/*_manifest.json
"""
import os
import sys

import psycopg2

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUCKET = "character-base"
METHOD_DOC = "CHARACTER_ASSET_METHOD.md"
GLOBAL_TAGS = ["character-base", "reference", "home_vocab", "line-art", "korean"]

# (key, view, pose, method, file_path[from project root])
CHARACTERS = [
    {
        "id": "jieun", "name_kr": "지은", "name_en": "Jieun", "gender": "female",
        "identity": ("long brown hair (key identifier), navy-and-white sailor "
                     "school uniform, red neckerchief, navy pleated skirt, knee "
                     "socks, brown shoes, friendly smile"),
        "style": ("minimalist 2D line art, thick clean black outlines, whiteboard "
                  "marker style, light beige background (#F5F5F0)"),
        "assets": [
            ("jieun_base_front",    "front", "standing", "text2img",      "home_vocab/jieun_base_front.png"),
            ("jieun_base_side",     "side",  "standing", "text2img",      "home_vocab/jieun_base_side.png"),
            ("jieun_base_back",     "back",  "standing", "text2img",      "home_vocab/jieun_base_back.png"),
            ("jieun_sitting_front", "front", "sitting",  "reference2img", "home_vocab/jieun_sitting_front.png"),
            ("jieun_sitting_side",  "side",  "sitting",  "reference2img", "home_vocab/jieun_sitting_side.png"),
            ("jieun_sitting_back",  "back",  "sitting",  "reference2img", "home_vocab/jieun_sitting_back.png"),
        ],
    },
    {
        "id": "injun", "name_kr": "인준", "name_en": "Injun", "gender": "male",
        "identity": ("short neat black hair (key feature), casual short-sleeve "
                     "t-shirt and pants (no school uniform)"),
        "style": ("minimalist 2D line art, thick black outlines, light beige "
                  "background (#F5F5F0)"),
        "assets": [
            ("injun_base_front", "front", "standing", "text2img", "home_vocab/injun_base_front.png"),
            ("injun_base_side",  "side",  "standing", "text2img", "home_vocab/injun_base_side.png"),
            ("injun_base_back",  "back",  "standing", "text2img", "home_vocab/injun_base_back.png"),
        ],
    },
]


def load_env(path=None):
    path = path or os.path.join(ROOT, ".env")
    env = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip().strip('"').strip("'")
    return env


CREATE_SQL = """
CREATE TABLE IF NOT EXISTS characters (
    id          TEXT PRIMARY KEY,
    name_kr     TEXT NOT NULL,
    name_en     TEXT NOT NULL,
    gender      TEXT,
    identity    TEXT,
    style       TEXT,
    tags        TEXT[],
    created_at  TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS character_assets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key          TEXT UNIQUE NOT NULL,
    character_id TEXT REFERENCES characters(id) ON DELETE CASCADE,
    view         TEXT NOT NULL,
    pose         TEXT NOT NULL,
    file_path    TEXT NOT NULL,
    storage_url  TEXT NOT NULL,
    method       TEXT NOT NULL,
    style        TEXT,
    tags         TEXT[],
    method_doc   TEXT,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_character_assets_id_view
    ON character_assets(character_id, view);
"""


def main():
    env = load_env()
    url = env["SUPABASE_URL"]
    service_key = env["SUPABASE_KEY"]  # service_role (스토리지 쓰기 권한)

    conn = psycopg2.connect(
        host=env["SUPABASE_DB_HOST"], port=env.get("SUPABASE_DB_PORT", "5432"),
        user=env["SUPABASE_DB_USER"], password=env["SUPABASE_DB_PASSWORD"],
        dbname=env.get("SUPABASE_DB_NAME", "postgres"), sslmode="require",
        connect_timeout=20,
    )
    cur = conn.cursor()
    cur.execute(CREATE_SQL)
    conn.commit()

    from supabase import create_client
    sb = create_client(url, service_key)
    try:
        names = [getattr(b, "name", None) for b in sb.storage.list_buckets()]
        if BUCKET not in names:
            sb.storage.create_bucket(BUCKET, options={"public": True})
            print(f"[bucket] created '{BUCKET}' (public)")
    except Exception as ex:
        print(f"[bucket] check/create skipped: {ex}")

    uploaded, inserted = 0, 0
    for ch in CHARACTERS:
        char_tags = sorted(set(GLOBAL_TAGS + [ch["id"], ch["gender"]]))
        cur.execute(
            """
            INSERT INTO characters (id, name_kr, name_en, gender, identity, style, tags)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (id) DO UPDATE SET
                name_kr = EXCLUDED.name_kr, name_en = EXCLUDED.name_en,
                gender = EXCLUDED.gender, identity = EXCLUDED.identity,
                style = EXCLUDED.style, tags = EXCLUDED.tags;
            """,
            (ch["id"], ch["name_kr"], ch["name_en"], ch["gender"],
             ch["identity"], ch["style"], char_tags),
        )
        conn.commit()
        print(f"[character] upserted {ch['name_kr']} ({ch['id']})")

        for key, view, pose, method, rel in ch["assets"]:
            local = os.path.join(ROOT, rel)
            if not os.path.exists(local):
                print(f"  [WARN] missing file, skip: {rel}")
                continue
            base = os.path.basename(rel)
            public_url = f"{url}/storage/v1/object/public/{BUCKET}/{base}"
            try:
                try:
                    sb.storage.from_(BUCKET).remove([base])
                except Exception:
                    pass
                with open(local, "rb") as fh:
                    sb.storage.from_(BUCKET).upload(
                        path=base, file=fh.read(),
                        file_options={"content-type": "image/png", "upsert": "true"},
                    )
                uploaded += 1
                print(f"  [upload] {base}")
            except Exception as ex:
                print(f"  [ERR] upload {base}: {ex}")

            asset_tags = sorted(set(char_tags + [view, pose, key]))
            cur.execute(
                """
                INSERT INTO character_assets
                    (key, character_id, view, pose, file_path, storage_url, method, style, tags, method_doc)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (key) DO UPDATE SET
                    character_id = EXCLUDED.character_id, view = EXCLUDED.view,
                    pose = EXCLUDED.pose, file_path = EXCLUDED.file_path,
                    storage_url = EXCLUDED.storage_url, method = EXCLUDED.method,
                    style = EXCLUDED.style, tags = EXCLUDED.tags,
                    method_doc = EXCLUDED.method_doc;
                """,
                (key, ch["id"], view, pose, rel, public_url, method,
                 ch["style"], asset_tags, METHOD_DOC),
            )
            conn.commit()
            inserted += 1
            print(f"  [asset] upserted {key} ({pose}/{view}, {method})")

    cur.execute("SELECT COUNT(*) FROM characters")
    n_char = cur.fetchone()[0]
    cur.execute("SELECT COUNT(*) FROM character_assets")
    n_asset = cur.fetchone()[0]
    cur.close()
    conn.close()
    print(f"\n[OK] storage uploads: {uploaded}, asset upserts: {inserted}")
    print(f"[OK] DB totals -> characters: {n_char}, character_assets: {n_asset}")


if __name__ == "__main__":
    main()
