#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""make_korea_places.py — 외국인이 좋아하는 한국 명소 140곳 → web/src/data/korea_places.json.

각 장소: 순번 + 한/영 이름 + 지역 + 분류 + 레저요소 + 한 줄 소개(한/영) + motif(파스텔 배경 생성용 비주얼 키워드).
배경 제작 시: 장소명 → 웹에서 아이코닉·레저 사진 참고 → motif로 파스텔 Flow 렌더 + 스크립트 사물.
재실행: python make_korea_places.py
"""
import os
import json

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "web", "src", "data", "korea_places.json")

REGION_EN = {
    "서울": "Seoul", "부산": "Busan", "제주": "Jeju", "경주": "Gyeongju", "안동": "Andong",
    "전주": "Jeonju", "충청": "Chungcheong", "강원": "Gangwon", "전남": "Jeolla", "경남": "Gyeongnam",
    "인천": "Incheon", "경기": "Gyeonggi", "전국": "Nationwide", "경북": "Gyeongbuk", "광주": "Gwangju",
}

# (name_ko, name_en, region, category, leisure_ko, why_ko, why_en, motif)
P = [
 # ── 서울 랜드마크 ──
 ("한강", "Han River", "서울", "강·공원", "피크닉·치맥·자전거·불꽃·유람선",
  "서울을 가로지르는 강. 돗자리 깔고 치맥, 자전거, 라면, 불꽃축제로 유명.",
  "Seoul's river — picnic mats, fried chicken & beer, biking, instant ramen, fireworks.",
  "wide calm river, city skyline far back, picnic mats, bicycles, a ramen cup, paddle boats, sunset"),
 ("경복궁", "Gyeongbokgung Palace", "서울", "궁궐·역사", "한복체험·수문장교대식",
  "조선의 정궁. 한복 입고 수문장 교대식을 보는 인생샷 명소.",
  "Joseon's main palace — wear hanbok, watch the royal guard ceremony.",
  "grand traditional Korean palace gate, tiled roofs, stone courtyard, hanbok colors, guards"),
 ("남산서울타워", "Namsan Seoul Tower", "서울", "전망·야경", "케이블카·사랑의자물쇠·야경",
  "남산 위 전망탑. 케이블카와 사랑의 자물쇠, 서울 야경의 상징.",
  "Hilltop tower — cable car, love padlocks, city night view.",
  "tall lookout tower on a green hill, cable car, fence of colorful love padlocks, city lights"),
 ("북촌한옥마을", "Bukchon Hanok Village", "서울", "한옥·골목", "한옥산책·한복",
  "기와집 골목이 보존된 마을. 한복 입고 옛 서울을 거니는 곳.",
  "Preserved hanok alleys — stroll old Seoul in hanbok.",
  "narrow sloping alley of traditional tiled-roof hanok houses, stone steps, potted plants"),
 ("명동", "Myeongdong", "서울", "쇼핑·먹거리", "길거리음식·화장품쇼핑",
  "쇼핑과 길거리 음식의 중심. 화장품, 떡볶이, 호떡이 가득.",
  "Shopping & street-food hub — cosmetics, tteokbokki, hotteok.",
  "busy bright shopping street, food carts, cosmetic shop signs, skewers and hotteok, crowds"),
 ("홍대", "Hongdae", "서울", "젊음·문화", "버스킹·클럽·카페",
  "젊음의 거리. 버스킹 공연과 개성 넘치는 카페·클럽.",
  "Youth district — street busking, indie cafes and clubs.",
  "lively street with buskers and a small crowd, mural walls, neon cafe signs, guitars"),
 ("인사동", "Insadong", "서울", "전통·예술", "전통찻집·공예·갤러리",
  "전통 찻집과 공예품, 갤러리가 모인 예술 거리.",
  "Arts street — traditional tea houses, crafts, galleries.",
  "traditional craft street, hanji lanterns, tea house, pottery and brush shops, ginkgo trees"),
 ("광장시장", "Gwangjang Market", "서울", "시장·먹거리", "빈대떡·마약김밥·먹자골목",
  "100년 전통시장. 빈대떡, 마약김밥, 육회로 유명한 먹자골목.",
  "Century-old market — mung-bean pancakes, mini gimbap, street feasts.",
  "covered traditional market alley, food stalls, sizzling pancakes, bowls, red stools, steam"),
 ("동대문디자인플라자", "Dongdaemun DDP", "서울", "현대·야경", "야간조명·패션·LED장미",
  "곡선형 미래 건축물. 야간 LED 장미정원과 패션 쇼핑.",
  "Futuristic curved landmark — LED rose garden at night, fashion shopping.",
  "sleek silver curved futuristic building at dusk, glowing LED roses, soft purple lights"),
 ("이태원", "Itaewon", "서울", "이국·나이트", "다국적음식·루프탑",
  "다국적 거리. 세계 음식과 루프탑 바, 이국적 분위기.",
  "Multicultural quarter — world food, rooftop bars.",
  "hilly international street, world-cuisine signs, rooftop terrace, string lights, mixed crowd"),
 ("성수동", "Seongsu-dong", "서울", "힙·카페", "팝업스토어·카페투어",
  "공장을 개조한 힙한 카페와 팝업스토어의 성지.",
  "Hip converted-factory cafes and pop-up stores.",
  "red-brick converted-warehouse cafe street, big windows, plants, pop-up store, industrial chic"),
 ("익선동", "Ikseon-dong", "서울", "한옥·카페", "골목한옥카페",
  "좁은 한옥 골목을 개조한 감성 카페 거리.",
  "Tiny hanok alleys turned into cozy cafes.",
  "very narrow hanok alley with cozy cafe entrances, hanging plants, warm lanterns, tiled roofs"),
 ("롯데월드타워 서울스카이", "Lotte World Tower Seoul Sky", "서울", "전망·야경", "전망대·야경",
  "한국에서 가장 높은 빌딩 전망대. 발아래 펼쳐진 서울.",
  "Korea's tallest tower observatory — Seoul at your feet.",
  "very tall glass skyscraper, observation deck view of city grid and river, glass floor, clouds"),
 ("청계천", "Cheonggyecheon Stream", "서울", "도심·산책", "도심물길산책",
  "도심을 흐르는 복원 하천. 물길 따라 걷는 산책로.",
  "Restored downtown stream — a walkway by the water.",
  "narrow restored stream below street level, stepping stones, willow, city buildings above"),
 ("광화문광장", "Gwanghwamun Square", "서울", "광장·역사", "세종대왕·이순신동상",
  "세종대왕과 이순신 동상이 있는 도심 광장.",
  "Civic square with statues of King Sejong and Admiral Yi.",
  "open city plaza, large bronze seated King statue, palace gate behind, fountains, flags"),
 # ── 서울 레저·공원 ──
 ("반포한강공원 무지개분수", "Banpo Rainbow Fountain", "서울", "강·공원", "분수쇼·피크닉",
  "다리에서 쏟아지는 무지개 분수쇼와 한강 피크닉.",
  "Bridge rainbow fountain show and riverside picnics.",
  "long bridge with arcs of rainbow-colored water fountains spraying into a river at dusk"),
 ("여의도한강공원", "Yeouido Hangang Park", "서울", "강·공원", "벚꽃·불꽃축제",
  "봄 벚꽃과 가을 세계불꽃축제로 붐비는 한강공원.",
  "Cherry blossoms in spring, fireworks festival in fall.",
  "riverside park lined with cherry-blossom trees, picnic crowds, city towers, soft pink petals"),
 ("뚝섬한강공원", "Ttukseom Hangang Park", "서울", "강·레저", "수상레저·자전거",
  "수상스키와 윈드서핑 등 수상레저를 즐기는 한강공원.",
  "Water sports — jet ski, windsurf — by the river.",
  "river park with windsurfers and small boats, bike path, green lawn, picnic tents"),
 ("망원한강공원", "Mangwon Hangang Park", "서울", "강·공원", "피크닉·라면",
  "편의점 라면과 돗자리 피크닉으로 인기인 한강공원.",
  "Convenience-store ramen and picnic-mat hangouts.",
  "grassy riverbank with picnic mats, a steaming ramen cup, friends sitting, bridge in distance"),
 ("올림픽공원", "Olympic Park", "서울", "공원·산책", "들꽃마루·나홀로나무",
  "넓은 잔디와 '나홀로 나무'가 있는 도심 속 공원.",
  "Vast lawns and the famous 'Lone Tree' photo spot.",
  "huge green rolling lawn with a single iconic tree on a hill, blue sky, wildflowers"),
 ("서울숲", "Seoul Forest", "서울", "공원·자연", "사슴·피크닉",
  "사슴이 사는 도심 숲. 가족 피크닉과 산책 명소.",
  "City forest with deer — family picnics and walks.",
  "leafy urban forest park, deer in a glade, wooden path, picnic families, tall trees"),
 ("롯데월드 어드벤처", "Lotte World", "서울", "테마파크", "놀이기구·아이스링크",
  "실내외 테마파크. 놀이기구와 아이스링크, 퍼레이드.",
  "Indoor/outdoor theme park — rides, ice rink, parades.",
  "fairy-tale theme park castle, roller coaster, hot-air-balloon ride, colorful parade"),
 ("에버랜드", "Everland", "경기", "테마파크", "판다·튤립·롤러코스터",
  "판다 푸바오와 튤립축제, 티익스프레스로 유명한 테마파크.",
  "Theme park — pandas, tulip festival, wooden coaster.",
  "big theme park with tulip fields, a panda, a tall wooden roller coaster, flower parade"),
 ("남산골한옥마을", "Namsangol Hanok Village", "서울", "한옥·전통", "전통체험·한복",
  "도심 속 전통 한옥과 정원에서 즐기는 전통 체험.",
  "Traditional hanok and gardens in the city center.",
  "cluster of hanok houses around a pond and garden, pavilion, traditional games, autumn trees"),
 ("북한산", "Bukhansan", "서울", "산·등산", "등산·도심전망",
  "서울을 둘러싼 화강암 산. 도심 전망 등산 명소.",
  "Granite mountain ringing Seoul — hiking with city views.",
  "rugged granite peaks above a green forest, hikers on a ridge, city skyline far below"),
 ("낙산공원 성곽길", "Naksan Park City Wall", "서울", "성곽·야경", "성곽야경산책",
  "한양도성 성곽을 따라 걷는 야경 산책로.",
  "Walk along the old city wall with night views.",
  "old stone fortress wall along a hill, lamp-lit path, city lights below, evening sky"),
 ("연트럴파크 경의선숲길", "Gyeongui Line Forest Park", "서울", "공원·산책", "숲길산책·카페",
  "옛 철길을 숲길로 바꾼 도심 산책로(연트럴파크).",
  "Old railway turned into a leafy walking park.",
  "long narrow green park on a former rail line, benches, cafes alongside, trees, couples walking"),
 ("코엑스 별마당도서관", "Starfield Library COEX", "서울", "실내·명소", "대형책장·포토존",
  "13m 대형 책장이 압도하는 실내 도서관 포토존.",
  "Giant 13m bookshelves — a striking indoor library.",
  "huge two-story open library hall with towering bookshelves, soft lighting, people reading"),
 # ── 서울 문화·현대 ──
 ("강남", "Gangnam", "서울", "도시·쇼핑", "쇼핑·카페·강남스타일",
  "고층 빌딩과 쇼핑·카페가 모인 트렌디한 도심.",
  "Glitzy district of towers, shopping and cafes.",
  "wide modern boulevard with glass towers, fashion boutiques, busy crosswalk, city energy"),
 ("가로수길", "Garosu-gil", "서울", "거리·카페", "은행나무길·쇼핑",
  "은행나무 늘어선 감각적인 카페·패션 거리.",
  "Ginkgo-lined trendy cafe and fashion street.",
  "tree-lined street with ginkgo trees, stylish boutiques and cafes, yellow autumn leaves"),
 ("삼청동", "Samcheong-dong", "서울", "골목·카페", "갤러리·카페골목",
  "궁 옆 한적한 골목의 갤러리와 카페 거리.",
  "Quiet palace-side alleys of galleries and cafes.",
  "calm uphill alley beside palace walls, small galleries, cozy cafes, stone wall, trees"),
 ("대학로", "Daehangno", "서울", "공연·문화", "소극장·연극",
  "소극장이 밀집한 연극과 공연의 거리.",
  "Theater district packed with small playhouses.",
  "street of small theaters with show posters, marquee lights, young crowd, plaza"),
 ("노량진수산시장", "Noryangjin Fish Market", "서울", "시장·먹거리", "활어회·해산물",
  "활어회를 골라 바로 먹는 대형 수산시장.",
  "Pick live seafood and eat it fresh — big fish market.",
  "huge indoor fish market, tanks of live seafood, ice stalls, vendors, bright lights"),
 ("통인시장", "Tongin Market", "서울", "시장·체험", "엽전도시락",
  "엽전을 받아 반찬을 사 먹는 도시락 체험 시장.",
  "Buy side dishes with old coins — lunchbox experience.",
  "cozy covered market alley, side-dish stalls, a lunchbox tray, brass coins, friendly vendors"),
 ("을지로 힙지로", "Euljiro (Hipjiro)", "서울", "레트로·힙", "노가리골목·레트로",
  "낡은 골목이 힙한 술집·카페로 변신한 '힙지로'.",
  "Gritty alleys reborn as hip bars and cafes.",
  "retro back-alley at night, hidden bar signs, old printing shops, warm neon, dried-snack pub"),
 ("연남동", "Yeonnam-dong", "서울", "카페·골목", "브런치·카페투어",
  "숲길 옆 브런치 카페와 아기자기한 골목.",
  "Brunch cafes and charming alleys by the forest path.",
  "leafy neighborhood of brunch cafes, outdoor tables, plants, low brick houses, sunny"),
 ("한남동", "Hannam-dong", "서울", "감각·갤러리", "편집숍·갤러리",
  "고급 편집숍과 갤러리, 디자인 카페의 거리.",
  "Upscale concept stores, galleries, design cafes.",
  "stylish hillside street, minimalist boutiques and gallery, clean facades, design cafe"),
 ("석촌호수", "Seokchon Lake", "서울", "호수·벚꽃", "벚꽃·러버덕",
  "롯데월드 옆 벚꽃 가득한 도심 호수.",
  "Cherry-blossom lake beside Lotte World.",
  "round city lake ringed with cherry blossoms, tower reflection, walking path, pink petals"),
 ("임진각 DMZ", "Imjingak DMZ", "경기", "역사·평화", "분단·평화공원",
  "분단의 현장. 평화의 메시지가 담긴 DMZ 관광지.",
  "Divided-border site — a peace park at the DMZ.",
  "peace park near the border, ribbons on a fence, old steam train, observation deck, wind pinwheels"),
 ("DDP 동대문 야시장", "Dongdaemun Night Market", "서울", "쇼핑·야시장", "심야쇼핑·먹거리",
  "밤새 열리는 패션 도매와 길거리 음식 야시장.",
  "All-night fashion wholesale and street-food market.",
  "bright night market, fashion stalls, food carts, busy late crowd, neon, paper cups of food"),
 # ── 부산 ──
 ("해운대해수욕장", "Haeundae Beach", "부산", "해변·도시", "해수욕·해변축제",
  "한국 대표 해변. 고층빌딩과 백사장, 여름 축제.",
  "Korea's iconic beach — skyline, sand, summer festivals.",
  "long sandy city beach, high-rise hotels behind, parasols, gentle waves, beachgoers"),
 ("광안리 광안대교", "Gwangalli & Diamond Bridge", "부산", "해변·야경", "야경·드론쇼",
  "광안대교 야경과 드론쇼로 유명한 해변.",
  "Beach famed for bridge night views and drone shows.",
  "beach at night facing a long lit suspension bridge, drone-light show in sky, cafes glowing"),
 ("감천문화마을", "Gamcheon Culture Village", "부산", "마을·예술", "색색마을·골목투어",
  "산비탈 색색 집들이 계단처럼 쌓인 예술 마을.",
  "Pastel houses stacked up a hillside — art village.",
  "hillside of colorful pastel cube houses stacked like steps, narrow stairs, murals, sea view"),
 ("자갈치시장", "Jagalchi Market", "부산", "시장·해산물", "활어회·해산물",
  "한국 최대 수산시장. 활어회와 꼼장어 구이.",
  "Korea's biggest fish market — live sashimi, grilled eel.",
  "bustling seaside fish market, tanks and ice, grilling eel, harbor boats, ajummas selling"),
 ("태종대", "Taejongdae", "부산", "자연·해안", "해안절벽·다누비열차",
  "기암절벽과 등대가 있는 해안 절경 공원.",
  "Cliffs and a lighthouse — dramatic coastal park.",
  "steep sea cliffs, white lighthouse, pine trees, blue ocean, a small train, viewpoint"),
 ("송도해상케이블카", "Songdo Marine Cable Car", "부산", "케이블카·해안", "해상케이블카·스카이워크",
  "바다 위를 가르는 케이블카와 구름다리.",
  "Cable car gliding over the sea, plus a skywalk.",
  "cable-car cabins crossing over blue sea between two headlands, beach and skywalk below"),
 ("흰여울문화마을", "Huinnyeoul Culture Village", "부산", "마을·해안", "해안절벽마을·골목",
  "영도 해안 절벽 위 하얀 집들의 골목 마을.",
  "White cliffside houses along Yeongdo's coast.",
  "white houses on a cliff edge above the sea, narrow path, blue water, boats, laundry lines"),
 ("국제시장 BIFF광장", "Gukje Market & BIFF Square", "부산", "시장·영화", "길거리음식·씨앗호떡",
  "영화제의 거리와 씨앗호떡 등 길거리 음식 시장.",
  "Film-festival street and street food (seed hotteok).",
  "lively market street, handprint plaques, hotteok griddle, food stalls, movie posters"),
 ("해동용궁사", "Haedong Yonggungsa", "부산", "사찰·해안", "바다절·일출",
  "바닷가 절벽 위에 지어진 아름다운 해안 사찰.",
  "Beautiful seaside temple built on coastal rocks.",
  "ornate Buddhist temple on sea cliffs, stone bridge, lanterns, waves crashing, sunrise"),
 ("다대포해수욕장", "Dadaepo Beach", "부산", "해변·노을", "노을·꿈의분수",
  "낙조와 꿈의낙조분수로 유명한 넓은 해변.",
  "Sunsets and a musical fountain on a wide beach.",
  "wide flat beach at sunset, shallow tide pools reflecting orange sky, fountain jets, silhouettes"),
 ("송정해수욕장", "Songjeong Beach", "부산", "해변·서핑", "서핑·해변카페",
  "초보 서퍼들이 즐겨 찾는 서핑 해변.",
  "Surf beach loved by beginner surfers.",
  "mellow beach with surfers and longboards, surf shops, gentle waves, palm-lined road"),
 ("용두산공원 부산타워", "Busan Tower Yongdusan", "부산", "전망·공원", "전망탑·야경",
  "원도심 언덕 위 부산타워와 공원 전망.",
  "Hilltop tower and park over the old downtown.",
  "park on a hill with a tall tower, pigeons, old downtown and harbor view, pine trees"),
 ("오륙도 스카이워크", "Oryukdo Skywalk", "부산", "해안·전망", "유리바닥·해안",
  "절벽 끝 유리 바닥에서 보는 다섯 섬과 바다.",
  "Glass-floor cliff walk over the sea and five isles.",
  "U-shaped glass skywalk off a cliff, blue sea below, rocky islets on the horizon"),
 ("블루라인파크 해변열차", "Blueline Park Beach Train", "부산", "해안·열차", "해변열차·스카이캡슐",
  "청사포 해안을 달리는 미니 해변열차와 스카이캡슐.",
  "Mini beach train and sky capsules along the coast.",
  "colorful sky-capsule pods and a small train on a coastal rail beside turquoise sea, cafes"),
 # ── 제주 ──
 ("성산일출봉", "Seongsan Ilchulbong", "제주", "자연·일출", "일출·분화구등반",
  "바다에서 솟은 거대한 분화구. 일출 명소.",
  "Giant tuff cone rising from the sea — sunrise spot.",
  "huge green volcanic crater rising from the sea, hiking path, sunrise glow, fields below"),
 ("한라산", "Hallasan", "제주", "산·등산", "등산·백록담",
  "제주의 중심 한국 최고봉. 백록담 분화구 등반.",
  "Korea's highest peak — crater-lake hike on Jeju.",
  "tall shield volcano above clouds, hiking trail through low brush, crater lake, autumn colors"),
 ("협재해수욕장", "Hyeopjae Beach", "제주", "해변·에메랄드", "에메랄드물·비양도",
  "에메랄드빛 바다와 비양도가 보이는 백사장.",
  "Emerald water with Biyangdo isle on the horizon.",
  "white-sand beach with emerald shallow water, a small island offshore, palm trees, clear sky"),
 ("우도", "Udo Island", "제주", "섬·자전거", "전기바이크·땅콩아이스크림",
  "전기자전거로 도는 작은 섬. 땅콩 아이스크림.",
  "Tiny island toured by e-bike — peanut ice cream.",
  "small green island coastline, rental scooters, lighthouse, white-and-emerald beach, stone walls"),
 ("만장굴", "Manjanggul Cave", "제주", "동굴·자연", "용암동굴탐험",
  "세계적 규모의 용암 동굴 탐험 코스.",
  "World-class lava tube to explore.",
  "dark basalt lava tube cave, lit walkway, towering lava column, dripping rock textures"),
 ("천지연폭포", "Cheonjiyeon Falls", "제주", "폭포·자연", "폭포산책",
  "아열대 숲 속으로 떨어지는 시원한 폭포.",
  "Cool waterfall amid subtropical forest.",
  "wide waterfall into a green pool, lush subtropical plants, wooden viewing deck, mist"),
 ("주상절리대", "Jusangjeolli Cliffs", "제주", "자연·해안", "육각절벽·파도",
  "파도가 부딪치는 육각형 주상절리 절벽.",
  "Hexagonal basalt sea cliffs battered by waves.",
  "dark hexagonal basalt columns by the sea, white waves crashing, viewpoint railing, blue water"),
 ("섭지코지", "Seopjikoji", "제주", "해안·언덕", "들판산책·등대",
  "노란 유채밭과 등대가 있는 해안 언덕.",
  "Coastal cape with canola fields and a lighthouse.",
  "grassy coastal cape, yellow canola flowers, white lighthouse, sea cliffs, Seongsan in distance"),
 ("애월 카페거리", "Aewol Cafe Street", "제주", "카페·해안", "오션뷰카페",
  "바다를 보며 즐기는 제주 오션뷰 카페 거리.",
  "Ocean-view cafe street on Jeju's coast.",
  "seaside cafes with big windows and terraces facing turquoise sea, palms, parked scooters"),
 ("오설록 티뮤지엄", "Osulloc Tea Museum", "제주", "녹차밭·카페", "녹차밭·녹차디저트",
  "드넓은 녹차밭과 녹차 디저트 카페·박물관.",
  "Vast green-tea fields with a tea museum and cafe.",
  "rolling green tea-plant rows in neat curves, modern cafe, green-tea desserts, blue sky"),
 ("비자림", "Bijarim Forest", "제주", "숲·산책", "비자나무숲산책",
  "수백 년 비자나무가 우거진 치유의 숲길.",
  "Healing trail through centuries-old nutmeg trees.",
  "dense ancient forest, red volcanic-soil path, mossy thick trees, dappled green light"),
 ("새별오름", "Saebyeol Oreum", "제주", "오름·억새", "억새·일몰",
  "은빛 억새와 일몰이 아름다운 제주 오름.",
  "Silver-grass volcanic hill with gorgeous sunsets.",
  "smooth grassy volcanic cone covered in silver pampas grass, sunset sky, trail to top"),
 ("함덕해수욕장", "Hamdeok Beach", "제주", "해변·오름", "에메랄드물·서우봉",
  "에메랄드 바다와 서우봉 산책이 어우러진 해변.",
  "Emerald beach next to the Seowoobong hill walk.",
  "shallow emerald beach beside a small green hill, white sand, palm cafes, paddleboards"),
 # ── 경주·안동·역사 ──
 ("불국사", "Bulguksa Temple", "경주", "사찰·유네스코", "고찰산책·다보탑",
  "통일신라 불교 예술의 정수. 유네스코 세계유산.",
  "Pinnacle of Silla Buddhist art — UNESCO site.",
  "grand old wooden temple, stone stairways and pagodas, autumn maples, lotus pond, tiled roofs"),
 ("석굴암", "Seokguram Grotto", "경주", "석굴·유네스코", "석굴본존불",
  "토함산 석굴 안의 거대한 본존불. 유네스코 유산.",
  "Great stone Buddha in a mountain grotto — UNESCO.",
  "domed stone grotto with a serene seated Buddha statue, soft light, mountain morning, pines"),
 ("첨성대", "Cheomseongdae", "경주", "유적·야경", "고대천문대·야경",
  "동양에서 가장 오래된 천문대. 야경 포토존.",
  "Asia's oldest observatory — lovely at night.",
  "ancient curved stone-bottle observatory tower on a lawn, flower field, night lighting, stars"),
 ("동궁과 월지", "Donggung & Wolji Pond", "경주", "유적·야경", "야경반영·연못",
  "물에 비친 누각이 환상적인 신라 별궁 야경.",
  "Silla palace pond — pavilions mirrored at night.",
  "lit wooden palace pavilions reflected in a calm pond at night, soft golden glow, reeds"),
 ("대릉원 천마총", "Daereungwon Tombs", "경주", "유적·능", "고분산책·능",
  "거대한 신라 고분이 잔디 언덕처럼 솟은 공원.",
  "Royal Silla burial mounds like grassy hills.",
  "rows of large grassy royal tomb mounds, walking path, a single tree, soft morning light"),
 ("황리단길", "Hwangnidan-gil", "경주", "한옥·카페", "한옥카페거리",
  "경주 고분 옆 한옥 카페와 소품샵 거리.",
  "Hanok cafe street beside Gyeongju's tombs.",
  "low hanok cafe street near grassy tomb mounds, hanbok renters, dessert cafes, lanterns"),
 ("안동하회마을", "Andong Hahoe Village", "안동", "민속·한옥", "전통마을·탈춤",
  "강이 휘감은 조선 양반 마을. 하회탈춤이 유명.",
  "River-wrapped Joseon village famed for mask dance.",
  "river-bend traditional village of thatched and tiled houses, mask dancers, old pine, river"),
 ("월영교", "Woryeonggyo Bridge", "안동", "다리·야경", "목교야경",
  "달빛 비치는 안동의 긴 나무 인도교 야경.",
  "Long wooden footbridge glowing under the moon.",
  "long arched wooden footbridge over a calm river at night, lantern lights, pavilion, reflection"),
 ("부석사", "Buseoksa Temple", "경북", "사찰·전망", "고찰·일몰전망",
  "능선 너머로 펼쳐진 일몰 전망의 천년 고찰.",
  "Ancient temple with sweeping sunset ridgeline views.",
  "old mountainside temple, wooden hall, rows of ridgelines fading into sunset haze, stone steps"),
 ("양동마을", "Yangdong Village", "경주", "민속·한옥", "전통한옥마을",
  "기와·초가가 어우러진 유네스코 양반 마을.",
  "UNESCO village of tiled and thatched noble houses.",
  "hillside traditional village, tiled and straw-roof houses among fields, stone walls, trees"),
 ("문경새재", "Mungyeong Saejae", "경북", "고개·트레킹", "옛길트레킹·관문",
  "조선 옛길을 걷는 산속 관문 트레킹 코스.",
  "Hike the old Joseon mountain pass and gates.",
  "old stone-and-wood fortress gate on a mountain trail, autumn foliage, dirt path, stream"),
 # ── 전주·충청 ──
 ("전주한옥마을", "Jeonju Hanok Village", "전주", "한옥·먹거리", "한복·비빔밥·길거리음식",
  "수백 채 한옥과 비빔밥, 길거리 음식의 한옥마을.",
  "Hundreds of hanok plus bibimbap and street food.",
  "wide hanok village of tiled roofs, hanbok visitors, food stalls, bibimbap bowl, lanterns"),
 ("경기전", "Gyeonggijeon Shrine", "전주", "사적·한옥", "어진·대나무숲",
  "태조 어진을 모신 사당과 대나무 숲 산책로.",
  "Shrine of the founding king with a bamboo grove.",
  "old shrine courtyard with tiled gate, bamboo grove path, stone lanterns, hanbok visitors"),
 ("자만벽화마을", "Jaman Mural Village", "전주", "마을·벽화", "벽화골목",
  "언덕 골목을 수놓은 알록달록 벽화 마을.",
  "Hillside alleys covered in colorful murals.",
  "steep alley with cheerful wall murals, small steps, cafes, potted flowers, hanok rooftops below"),
 ("공산성", "Gongsanseong Fortress", "충청", "성곽·역사", "성곽산책·백제",
  "금강을 굽어보는 백제의 산성 성곽길.",
  "Baekje hilltop fortress overlooking the river.",
  "earthen-and-stone fortress wall along a green hill, river bend below, pavilion, flags, pines"),
 ("궁남지", "Gungnamji Pond", "충청", "연못·정원", "연꽃·야경",
  "연꽃 가득한 백제의 인공 연못과 정자 야경.",
  "Baekje lotus pond with a pavilion, lovely at night.",
  "large lotus-filled pond with a wooden pavilion on an island, arched bridge, pink lotus, dusk"),
 ("대전 성심당", "Daejeon Sungsimdang", "충청", "베이커리·명물", "튀김소보로·빵투어",
  "전국에서 찾아오는 대전의 명물 빵집.",
  "Daejeon's legendary bakery people travel for.",
  "warm bustling bakery, trays of golden pastries, long happy queue, bread baskets, cozy lights"),
 ("도담삼봉", "Dodamsambong", "충청", "강·기암", "강위세봉우리·유람선",
  "강 위에 솟은 세 봉우리 기암과 정자.",
  "Three rocky peaks rising from a river with a pavilion.",
  "three pointed rock peaks in a wide river, small pavilion on the central peak, mountains, boat"),
 ("만천하스카이워크", "Mancheonha Skywalk", "충청", "전망·스릴", "유리전망·집와이어",
  "강을 내려다보는 아찔한 유리 전망대.",
  "Glass skywalk perched high above the river.",
  "spiral glass skywalk tower over a green river valley, vertigo view, forested hills, zip-line"),
 # ── 강원 ──
 ("설악산", "Seoraksan", "강원", "산·단풍", "단풍·케이블카·울산바위",
  "기암과 단풍, 권금성 케이블카로 유명한 명산.",
  "Famed peaks, autumn colors, and a cable car.",
  "jagged granite peaks blazing with red-orange autumn foliage, cable car, temple, stream, blue sky"),
 ("남이섬", "Nami Island", "강원", "섬·산책", "메타세쿼이아길·자전거",
  "메타세쿼이아 길과 드라마로 유명한 낭만의 섬.",
  "Romantic island of metasequoia lanes and drama fame.",
  "long straight tree-lined lane of tall metasequoia, couple walking, bicycles, autumn or snow"),
 ("경포대 경포해변", "Gyeongpodae & Gyeongpo Beach", "강원", "해변·호수", "해변·호수산책",
  "넓은 백사장과 경포호가 어우러진 강릉 명소.",
  "Wide beach paired with a calm lagoon in Gangneung.",
  "long sandy east-sea beach beside a calm lagoon, pine forest, pavilion, sunrise over water"),
 ("안목해변 커피거리", "Anmok Coffee Street", "강원", "해변·카페", "오션뷰카페·커피",
  "바다를 보며 커피를 즐기는 강릉 커피 거리.",
  "Seaside coffee street in Gangneung.",
  "row of cafes facing the sea, big windows, coffee cups, beach and breakwater, gulls"),
 ("정동진", "Jeongdongjin", "강원", "일출·기차", "기차일출·바다",
  "바다와 맞닿은 역에서 보는 유명한 일출.",
  "Sunrise at the station right by the sea.",
  "small train station meters from the sea, tracks along the shore, sunrise over water, train"),
 ("속초중앙시장", "Sokcho Jungang Market", "강원", "시장·먹거리", "닭강정·만석닭강정",
  "닭강정과 오징어순대로 유명한 동해 시장.",
  "Famous for sweet fried chicken and squid sundae.",
  "lively market arcade, glossy sweet-chicken stalls, seafood, paper cups, steam, vendors"),
 ("대관령 양떼목장", "Daegwallyeong Sheep Farm", "강원", "목장·자연", "양떼·초원산책",
  "능선 초원에서 양에게 먹이를 주는 목장.",
  "Feed sheep on rolling highland meadows.",
  "rolling green highland meadow with white sheep, wooden fences, wind turbines on ridge, blue sky"),
 ("월정사 전나무숲길", "Woljeongsa Fir Forest", "강원", "사찰·숲", "전나무숲길",
  "오대산 천년 전나무가 우거진 명상 숲길.",
  "Meditative trail of ancient fir trees at Odaesan.",
  "tall straight fir-tree forest path, soft earth trail, temple gate, mist, green light"),
 ("정선 레일바이크", "Jeongseon Rail Bike", "강원", "레일바이크·자연", "레일바이크",
  "폐철로를 달리는 산골 풍경 레일바이크.",
  "Pedal a rail bike through mountain valley scenery.",
  "rail bikes on old train tracks through a green valley, river beside, tunnels, autumn hills"),
 ("춘천 닭갈비골목", "Chuncheon Dakgalbi Alley", "강원", "먹거리·호수", "닭갈비·소양강",
  "닭갈비와 막국수, 소양강 풍경의 호반 도시.",
  "Spicy chicken galbi alley in a lakeside city.",
  "sizzling chicken-galbi griddle alley, cabbage and rice cake, steam, lake and bridge nearby"),
 ("양양 서피비치", "Yangyang Surfyy Beach", "강원", "해변·서핑", "서핑·비치파티",
  "서핑과 비치 파티로 뜨는 동해 서핑 성지.",
  "East-coast surf mecca with beach-party vibes.",
  "wide surf beach with surfboards, beach bar with parasols and bean bags, sunset, surfers"),
 ("인제 자작나무숲", "Inje Birch Forest", "강원", "숲·트레킹", "자작나무숲트레킹",
  "하얀 자작나무가 빼곡한 청량한 숲 트레킹.",
  "Trek through a forest of white birch trees.",
  "dense forest of slender white birch trunks, snow or green floor, soft light, winding trail"),
 # ── 호남·남부 ──
 ("여수 밤바다", "Yeosu Night Sea", "전남", "야경·해안", "밤바다·돌산대교야경",
  "노래로 유명한 여수의 낭만적인 밤바다.",
  "The romantic night sea made famous by a song.",
  "harbor at night, lit bridge over dark water, waterfront cafes and lights reflected, boats"),
 ("여수 해상케이블카", "Yeosu Cable Car", "전남", "케이블카·해안", "해상케이블카·야경",
  "바다 위를 건너는 크리스털 해상 케이블카.",
  "Crystal cabins crossing over the sea.",
  "cable car with clear-floor cabins over a blue strait between two hills, harbor and bridge below"),
 ("순천만습지", "Suncheonman Wetland", "전남", "습지·자연", "갈대밭·S자노을",
  "광활한 갈대밭과 S자 물길 노을의 습지.",
  "Vast reed beds and the S-curve channel at sunset.",
  "endless golden reed wetland with an S-shaped water channel, sunset, boardwalk, flying cranes"),
 ("보성 녹차밭", "Boseong Green Tea Fields", "전남", "녹차밭·자연", "녹차밭계단·산책",
  "산비탈을 따라 계단처럼 펼쳐진 녹차밭.",
  "Terraced green-tea fields cascading down hills.",
  "steep hillside of curved green tea-plant terraces, tall cedar trees lining a path, misty green"),
 ("담양 죽녹원", "Juknokwon Bamboo Forest", "전남", "대나무숲·산책", "대나무숲길",
  "쭉쭉 뻗은 대나무가 하늘을 가린 청량한 숲길.",
  "Cool trails under towering green bamboo.",
  "tall dense green bamboo forest, sunlit path, wooden walkway, soft green shade, lantern"),
 ("메타세쿼이아길", "Metasequoia Road", "전남", "가로수길·산책", "메타세쿼이아가로수",
  "담양의 곧게 뻗은 메타세쿼이아 가로수길.",
  "Damyang's straight avenue of metasequoia trees.",
  "long straight road lined with tall symmetrical metasequoia trees, cyclists, autumn russet"),
 ("동피랑벽화마을", "Dongpirang Mural Village", "경남", "마을·벽화", "벽화·항구전망",
  "통영 항구가 내려다보이는 언덕 벽화 마을.",
  "Hillside mural village over Tongyeong harbor.",
  "steep alley of murals on a hill above a fishing harbor, colorful walls, boats and sea below"),
 ("통영 케이블카 미륵산", "Tongyeong Cable Car", "경남", "케이블카·전망", "케이블카·한려수도",
  "한려수도 다도해를 한눈에 보는 케이블카.",
  "Cable car over Tongyeong's island-dotted sea.",
  "cable car rising to a peak overlooking a sea scattered with many small green islands"),
 ("외도 보타니아", "Oedo Botania", "경남", "섬·정원", "해상정원·동백",
  "거제 앞바다의 지중해풍 해상 식물 정원섬.",
  "Mediterranean-style garden island off Geoje.",
  "lush garden island with topiary, white statues, cypress, flower beds, blue sea all around"),
 ("바람의언덕", "Windy Hill Geoje", "경남", "해안·언덕", "풍차·해안언덕",
  "풍차와 초원이 바다와 어우러진 해안 언덕.",
  "Grassy coastal hill with a windmill by the sea.",
  "grassy seaside hill with a white windmill, wooden path, blue sea and islets, wind, couples"),
 ("남해 다랑이마을", "Namhae Darangyi Village", "경남", "마을·다랑논", "계단식논·해안마을",
  "바다로 떨어지는 계단식 다랑이 논의 해안 마을.",
  "Coastal village of terraced rice paddies to the sea.",
  "terraced rice paddies stepping down a steep coast to the sea, stone walls, village houses"),
 ("광주 양림동", "Gwangju Yangnim-dong", "광주", "근대·골목", "근대건축·카페골목",
  "근대 건축과 예술이 어우러진 감성 골목 동네.",
  "Historic modern architecture and arty alleys.",
  "quiet old-modern neighborhood, brick missionary houses, mural alleys, cafes, big trees"),
 # ── 인천·경기·기타 ──
 ("인천 차이나타운", "Incheon Chinatown", "인천", "거리·먹거리", "짜장면·동화마을",
  "짜장면 발상지와 송월동 동화마을이 있는 거리.",
  "Birthplace of jjajangmyeon, beside a fairy-tale village.",
  "red-and-gold Chinatown gate and street, lanterns, jjajangmyeon, nearby pastel fairy-tale walls"),
 ("월미도", "Wolmido", "인천", "해안·놀이", "디스코팡팡·유람선",
  "바다 놀이기구와 조개구이의 인천 바닷가 놀이터.",
  "Seaside fun rides and grilled clams in Incheon.",
  "seaside boardwalk with amusement rides, a spinning disco ride, grilled-clam stalls, ferry, gulls"),
 ("송도 센트럴파크", "Songdo Central Park", "인천", "공원·현대", "수상택시·고층뷰",
  "고층 빌딩에 둘러싸인 해수 운하 도심 공원.",
  "Seawater-canal park ringed by skyscrapers.",
  "modern park with a seawater canal, water taxi, sleek glass towers around, lawns, kayaks"),
 ("강화도 전등사", "Ganghwa Jeondeungsa", "인천", "사찰·역사", "고찰·고인돌",
  "산성 안 천년 고찰과 고인돌의 역사 섬.",
  "Ancient temple in a fortress on a history-rich island.",
  "old wooden temple within forested hills, fortress wall, dolmen stone, lotus lanterns"),
 ("수원화성", "Suwon Hwaseong Fortress", "경기", "성곽·유네스코", "성곽순환·야경",
  "조선의 과학이 담긴 유네스코 성곽 산책로.",
  "UNESCO fortress wall showcasing Joseon engineering.",
  "long stone fortress wall with arched gates and watchtowers over a city, archery, night lights"),
 ("한국민속촌", "Korean Folk Village", "경기", "민속·체험", "전통공연·민속체험",
  "조선 마을을 재현한 전통 체험과 공연의 민속촌.",
  "Recreated Joseon village with shows and crafts.",
  "recreated folk village of hanok and thatch houses, clay jars, traditional performers, ox cart"),
 ("헤이리예술마을", "Heyri Art Village", "경기", "예술·갤러리", "갤러리·카페건축",
  "건축과 갤러리, 카페가 어우러진 예술인 마을.",
  "Artists' village of striking architecture and galleries.",
  "village of artistic modern buildings, sculpture gardens, design cafes, galleries, trees"),
 ("쁘띠프랑스", "Petite France", "경기", "테마·유럽풍", "유럽풍마을·어린왕자",
  "어린 왕자 테마의 알록달록 유럽풍 마을.",
  "Colorful French-themed Little Prince village.",
  "cluster of colorful European-style houses on a hill, Little Prince statue, lake view, flowers"),
 ("아침고요수목원", "Garden of Morning Calm", "경기", "수목원·정원", "정원산책·오색별빛",
  "사계절 정원과 겨울 빛축제가 아름다운 수목원.",
  "Year-round gardens famed for a winter light festival.",
  "landscaped flower gardens on hills, winding paths, in winter draped with colorful fairy lights"),
 ("허브아일랜드", "Herb Island", "경기", "테마·정원", "허브·빛축제",
  "허브 정원과 불빛 축제로 유명한 테마 정원.",
  "Herb gardens and a sparkling light festival.",
  "herb-garden village with greenhouses, lavender, evening lantern lights, fountains, photo arches"),
 ("양평 두물머리", "Yangpyeong Dumulmeori", "경기", "강·일출", "물안개·느티나무",
  "두 강이 만나는 물안개와 고목의 일출 명소.",
  "Where two rivers meet — misty sunrise and old tree.",
  "calm wide river confluence at dawn, morning mist, a huge old zelkova tree, small wooden boat"),
 # ── 체험·계절·문화 ──
 ("찜질방", "Jjimjilbang", "전국", "체험·휴식", "한국식사우나·식혜",
  "양머리 수건과 식혜, 한국식 사우나 찜질 문화.",
  "Korean sauna culture — towel hats and sweet rice drink.",
  "warm spa lounge, people in matching pajamas with towel 'sheep' hats, heated floor, sikhye drink"),
 ("한강 라면 편의점", "Hangang Ramen & CU", "서울", "문화·먹거리", "즉석라면·돗자리",
  "한강 편의점 즉석 라면조리기와 돗자리 야식 문화.",
  "Riverside convenience-store ramen and mat snacking.",
  "riverside convenience store at night, ramen-cooking machine, picnic mat, beer, city lights"),
 ("노래방", "Noraebang", "전국", "체험·놀이", "코인노래방·탬버린",
  "친구들과 목청껏 부르는 한국식 코인 노래방.",
  "Korean song rooms — belt it out with friends.",
  "small song room glowing with neon and a disco ball, big screen lyrics, microphones, tambourine"),
 ("PC방", "PC Bang", "전국", "체험·게임", "게임·라면",
  "최신 사양 컴퓨터와 라면이 함께인 게임 문화.",
  "Gaming cafes with top PCs and ramen.",
  "rows of gaming PCs with glowing keyboards, gamers in chairs, a bowl of ramen, dim neon lighting"),
 ("치맥", "Chimaek (Chicken & Beer)", "전국", "먹거리·문화", "치킨·맥주·야식",
  "바삭한 치킨과 시원한 맥주, 한국 야식의 왕.",
  "Crispy fried chicken with cold beer — Korea's night feast.",
  "table with golden fried chicken, frothy beer mugs, pickled radish, friends toasting, warm pub"),
 ("포장마차", "Pojangmacha", "전국", "먹거리·문화", "길거리포차·소주",
  "주황 천막 아래 떡볶이·어묵·소주의 길거리 포차.",
  "Orange-tent street stalls — snacks and soju.",
  "orange-tent street food stall at night, steaming fish cakes and tteokbokki, soju, stools, lantern"),
 ("전통시장", "Traditional Market", "전국", "시장·먹거리", "재래시장·길거리음식",
  "정겨운 흥정과 길거리 음식이 가득한 재래시장.",
  "Bustling old markets full of haggling and street food.",
  "covered traditional market alley, produce and food stalls, hanging signs, busy shoppers, steam"),
 ("템플스테이", "Templestay", "전국", "체험·힐링", "산사체험·발우공양",
  "산사에서 묵으며 명상과 발우공양을 하는 체험.",
  "Stay at a mountain temple — meditation and monk meals.",
  "mountain temple courtyard at dawn, monk and visitors in grey robes, lotus lanterns, misty pines"),
 ("진해 군항제", "Jinhae Cherry Blossom Festival", "경남", "축제·벚꽃", "벚꽃터널·기차역",
  "벚꽃 터널과 경화역으로 유명한 봄 벚꽃 축제.",
  "Spring festival of cherry-blossom tunnels and a rail station.",
  "tunnel of cherry-blossom trees over old train tracks, falling pink petals, crowds, stream bridge"),
 ("화천 산천어축제", "Hwacheon Sancheoneo Ice Festival", "강원", "축제·겨울", "얼음낚시·눈썰매",
  "꽁꽁 언 강에서 즐기는 겨울 얼음낚시 축제.",
  "Winter ice-fishing festival on a frozen river.",
  "frozen river dotted with ice-fishing holes, people bundled up, ice sculptures, snow, sledding"),
 # ── 추가 명소 ──
 ("부산 더베이101", "The Bay 101 Busan", "부산", "야경·요트", "요트·마천루야경",
  "요트와 마천루 야경이 물에 비치는 부산 핫플.",
  "Yachts and skyline reflections — Busan's night hotspot.",
  "marina at night, yachts, glowing high-rise towers reflected on calm water, waterfront cafe"),
 ("카멜리아힐", "Camellia Hill", "제주", "정원·동백", "동백꽃·수목정원",
  "겨울 붉은 동백이 만개하는 제주 수목 정원.",
  "Jeju garden where red camellias bloom in winter.",
  "garden hill of blooming red camellia trees, fallen red petals on a path, ponds, pampas grass"),
 ("군산 근대역사거리", "Gunsan Modern History Street", "전남", "근대·골목", "시간여행·근대건축",
  "일제강점기 근대 건물이 남은 시간여행 거리.",
  "Time-travel街 of preserved early-modern buildings.",
  "old early-1900s street, brick bank and warehouses, vintage signs, rail crossing, retro mood"),
 ("포항 호미곶", "Homigot Cape", "경북", "일출·해안", "상생의손·일출",
  "바다에서 솟은 '상생의 손'과 일출 명소.",
  "Sunrise cape with the giant 'Hand of Harmony' sculpture.",
  "rocky cape at sunrise, a large bronze hand sculpture rising from the sea, orange sky, lighthouse"),
 ("울산 간절곶", "Ganjeolgot Cape", "경남", "일출·등대", "일출·하얀등대",
  "한반도에서 해가 가장 먼저 뜨는 하얀 등대 곶.",
  "Where Korea's mainland sunrise comes first — white lighthouse.",
  "grassy coastal cape with a tall white lighthouse, sunrise over the sea, mailbox sculpture, path"),
 ("대구 김광석거리", "Daegu Kim Kwang-seok Street", "경북", "벽화·음악", "음악벽화골목·버스킹",
  "가수 김광석을 기리는 음악 벽화와 버스킹 골목.",
  "Mural alley honoring a beloved singer — busking spot.",
  "narrow alley of music-themed murals, a guitar statue, busking corner, warm string lights"),
 ("거제 매미성", "Geoje Maemiseong", "경남", "해안·성벽", "해안돌성·포토존",
  "한 사람이 쌓은 동화 같은 해안 돌 성벽.",
  "Fairy-tale stone seawall built by one man.",
  "rustic curved stone castle wall on a rocky coast, blue sea, small turret, climbing path"),
 ("영월 한반도지형", "Yeongwol Korea-Shape Land", "강원", "전망·자연", "한반도뷰·뗏목",
  "강이 휘감아 한반도 모양을 이룬 전망 명소.",
  "River bend shaped exactly like the Korean peninsula.",
  "forested river peninsula shaped like the Korea map, viewpoint deck, raft, green water, hills"),
 ("태안 꽃지해변", "Taean Kkotji Beach", "충청", "해변·노을", "노을·할미할아비바위",
  "할미·할아비 바위 사이로 지는 서해 일몰 명소.",
  "West-sea sunset framed by two famous rocks.",
  "wide tidal beach at sunset, two rock islets silhouetted, orange-pink sky reflected on wet sand"),
 # ── 밀양 10경 (밀양시) ──
 ("영남루", "Yeongnamnu Pavilion", "경남", "누각·강", "강변누각·야경",
  "밀양강을 굽어보는 조선 3대 누각. 야경이 일품.",
  "Grand riverside pavilion over the Miryang River — lovely at night.",
  "elegant wooden riverside pavilion with sweeping tiled roof above a calm river, night lights, reflection"),
 ("밀양 표충사", "Pyochungsa Temple Miryang", "경남", "사찰·단풍", "산사·단풍",
  "재약산 자락의 호국 사찰. 가을 단풍이 아름답다.",
  "Mountain temple at Jaeyaksan, glorious in autumn.",
  "old temple courtyard at the foot of a mountain, red-orange autumn maples, stone pagoda, stream"),
 ("밀양 얼음골", "Eoreumgol Ice Valley", "경남", "계곡·자연", "한여름얼음·계곡",
  "한여름에도 얼음이 어는 신비한 계곡.",
  "Mysterious valley where ice forms even in midsummer.",
  "rocky shaded mountain valley with ice patches among boulders, cold stream, green cliffs, mist"),
 ("밀양 호박소", "Hobakso Pool", "경남", "계곡·소", "에메랄드소·계곡",
  "옥빛 물이 고인 화강암 협곡의 깊은 소.",
  "Jade-green pool in a granite gorge.",
  "deep emerald pool in a smooth granite gorge, small waterfall, green forest, clear water"),
 ("밀양 위양지", "Wiyangji Pond", "경남", "연못·이팝나무", "이팝나무·반영",
  "이팝나무 꽃이 물에 비치는 고요한 저수지 정원.",
  "Serene reservoir garden mirrored by snowbell blossoms.",
  "calm pond with a tiny island pavilion, white snowbell trees in bloom reflected on still water"),
 ("밀양 만어사", "Maneosa Temple", "경남", "사찰·너덜", "종석너덜·전망",
  "두드리면 종소리 나는 돌무더기 너덜의 산사.",
  "Hilltop temple above a field of bell-ringing stones.",
  "mountain temple above a vast slope of grey boulders, valley view, pagoda, morning light"),
 ("밀양 월연정", "Wolyeonjeong Pavilion", "경남", "정자·강", "강변정자·터널",
  "강가 절벽 위 정자와 옛 철길 백송터널.",
  "Cliffside pavilion by the river with an old rail tunnel.",
  "wooden pavilion on a wooded riverside cliff, old stone rail tunnel, pine trees, calm river"),
 ("밀양 종남산 진달래", "Jongnamsan Azaleas", "경남", "산·진달래", "진달래능선·전망",
  "봄이면 분홍 진달래로 뒤덮이는 능선 전망.",
  "Ridges blanketed in pink azaleas each spring.",
  "mountain ridge covered in pink azalea blossoms, winding trail, valley and river view below"),
 ("밀양 재약산 사자평", "Sajapyeong Highland", "경남", "고원·억새", "억새평원·영남알프스",
  "영남알프스 재약산의 드넓은 가을 억새 평원.",
  "Vast autumn silver-grass plateau in the Yeongnam Alps.",
  "wide highland plateau of silvery pampas grass, rolling ridges, hikers, blue autumn sky"),
 ("밀양댐", "Miryang Dam Lake", "경남", "호수·드라이브", "호수드라이브·전망",
  "산을 두른 잔잔한 호수와 드라이브 전망.",
  "Tranquil mountain-ringed lake and scenic drive.",
  "calm reservoir lake among green mountains, winding lakeside road, viewpoint, reflection"),
 # ── 양산 8경 (양산시) ──
 ("양산 통도사", "Tongdosa Temple", "경남", "사찰·유네스코", "삼보사찰·매화",
  "부처 진신사리를 모신 삼보사찰. 봄 홍매화로 유명.",
  "Great UNESCO temple housing Buddha's relics — famed plum blossoms.",
  "grand sprawling temple complex among pines, pink plum blossoms, stone bridge, lanterns, hall"),
 ("양산 내원사 계곡", "Naewonsa Valley", "경남", "계곡·단풍", "맑은계곡·단풍",
  "천성산 자락 맑은 물과 단풍이 어우러진 계곡.",
  "Clear-water valley with autumn foliage below Cheonseongsan.",
  "clear rocky mountain stream with pools, red-yellow autumn trees, wooden bridge, temple gate"),
 ("양산 천성산", "Cheonseongsan", "경남", "산·억새", "화엄벌억새·습지",
  "정상 화엄벌 억새와 고산 습지의 명산.",
  "Peak with silver-grass meadows and alpine wetlands.",
  "broad mountaintop meadow of silver grass and small wetland ponds, distant ridges, blue sky"),
 ("양산 영축산", "Yeongchuksan", "경남", "산·능선", "영남알프스능선",
  "영남알프스의 웅장한 바위 능선 전망.",
  "Majestic rocky ridge of the Yeongnam Alps.",
  "long grassy-and-rock mountain ridge under big sky, hikers on the crest, sea of distant peaks"),
 ("양산 홍룡폭포", "Hongnyong Falls", "경남", "폭포·무지개", "폭포무지개·기도처",
  "물보라에 무지개가 뜨는 3단 폭포와 산사.",
  "Three-tier falls with rainbow mist beside a temple.",
  "tall three-tier waterfall with rainbow in the spray, small shrine behind the water, green cliffs"),
 ("양산 배내골", "Baenaegol Valley", "경남", "계곡·캠핑", "청정계곡·물놀이",
  "영남알프스 품속 맑은 물의 청정 계곡 휴양지.",
  "Pristine valley retreat deep in the Yeongnam Alps.",
  "clear cool valley stream among forested mountains, smooth rocks, swimming pools, camp tents"),
 ("양산 황산공원", "Hwangsan Park", "경남", "강변·공원", "강변꽃밭·자전거",
  "낙동강변 드넓은 꽃밭과 자전거길의 강변 공원.",
  "Riverside park of flower fields and bike paths by the Nakdong.",
  "vast riverside park with colorful flower fields, bike path, river and bridge, picnic lawn"),
 ("양산 신불산 억새", "Sinbulsan Silver Grass", "경남", "산·억새", "억새평원·일몰",
  "영남알프스 신불산 정상의 황금빛 억새 평원.",
  "Golden silver-grass plains atop Sinbulsan.",
  "endless golden silver-grass field on a high ridge at sunset, trail, glowing seed heads, peaks"),
 # ── 부산 10곳 추가 ──
 ("부산 이기대 해안산책로", "Igidae Coastal Trail", "부산", "해안·트레킹", "해안절벽산책·스카이라인",
  "광안대교를 바라보며 걷는 해안 절벽 산책로.",
  "Cliff-edge coastal walk facing the Diamond Bridge.",
  "rugged coastal cliff trail with wooden walkways, blue sea, distant bridge and skyline, pine"),
 ("부산 동백섬 누리마루", "Dongbaekseom Nurimaru", "부산", "해안·산책", "동백숲산책·APEC",
  "해운대 동백숲 산책로와 누리마루 전망.",
  "Camellia-forest walk and the Nurimaru landmark by Haeundae.",
  "wooded seaside island path with camellia trees, a domed pavilion on rocks, sea and skyline"),
 ("부산시민공원", "Busan Citizens Park", "부산", "공원·산책", "도심공원·분수",
  "도심 속 넓은 잔디와 분수, 산책로의 시민공원.",
  "Big downtown park of lawns, fountains and paths.",
  "spacious city park with green lawns, a long fountain canal, tree-lined paths, families"),
 ("부산 보수동 책방골목", "Bosu-dong Book Alley", "부산", "골목·책방", "헌책방골목",
  "헌책이 빼곡한 좁은 골목의 정겨운 책방거리.",
  "Charming narrow alley packed with secondhand bookshops.",
  "narrow alley with secondhand bookshops, books stacked floor to ceiling, hand-painted signs"),
 ("부산 황령산 야경", "Hwangnyeongsan Night View", "부산", "전망·야경", "도심야경전망",
  "부산 도심과 바다가 한눈에 보이는 야경 전망대.",
  "Lookout over the city and sea — Busan's best night view.",
  "hilltop view of a glittering night city wrapping around a dark bay, lit bridge, observation deck"),
 ("부산 송도해수욕장", "Songdo Beach Busan", "부산", "해변·케이블카", "구름산책로·해변",
  "구름산책로와 해상케이블카가 있는 원조 해수욕장.",
  "Korea's first beach, with a cloud walkway and cable car.",
  "curved sandy bay beach, a curving over-water cloud walkway, cable car overhead, blue sea"),
 ("부산 깡깡이예술마을", "Kkangkkangi Art Village", "부산", "마을·예술", "조선소마을·벽화",
  "옛 수리조선소 골목이 예술로 되살아난 영도 마을.",
  "Old shipyard alleys reborn as art in Yeongdo.",
  "harbor-side old shipyard alley with murals and art, rusty boats, cranes, narrow streets, sea"),
 ("부산 절영해안산책로", "Jeoryeong Coastal Walk", "부산", "해안·산책", "해안데크·기암",
  "영도 기암 해안을 따라 걷는 데크 산책로.",
  "Deck trail along Yeongdo's craggy coast.",
  "wooden deck path hugging rocky sea cliffs, crashing waves, fishing platforms, pine, open sea"),
 ("부산 북항", "Busan North Port", "부산", "항구·야경", "항구야경·관람차",
  "재개발된 항구의 야경과 해상 명소.",
  "Redeveloped harbor with night views and waterfront sights.",
  "modern harbor waterfront at night, cruise ship, lit cranes and towers reflected on water"),
 ("기장 죽성성당", "Jukseong Church Gijang", "부산", "해안·포토", "바다성당·포토존",
  "바닷가 언덕 위 그림 같은 작은 성당 포토존.",
  "Picture-perfect little seaside church on a grassy bluff.",
  "small white-and-red European-style chapel on a grassy seaside bluff, blue sea, rocks, flowers"),
]


# 외국인 인기순 상위(앞쪽). 상위 24곳 = 24주 월요일 배경. 나머지는 원래 순서로 뒤에 배치.
POP_ORDER = [
    "경복궁", "한강", "명동", "남산서울타워", "북촌한옥마을", "홍대", "인사동", "광장시장",
    "해운대해수욕장", "광안리 광안대교", "감천문화마을", "성산일출봉", "협재해수욕장", "한라산",
    "불국사", "전주한옥마을", "남이섬", "설악산", "강남", "이태원", "성수동",
    "롯데월드타워 서울스카이", "에버랜드", "동대문디자인플라자",
    # 25위~
    "광화문광장", "청계천", "자갈치시장", "해동용궁사", "첨성대", "동궁과 월지", "수원화성",
    "한국민속촌", "인천 차이나타운", "가로수길", "익선동", "롯데월드 어드벤처", "우도", "섭지코지",
    "여수 밤바다", "대릉원 천마총", "황리단길", "안동하회마을", "을지로 힙지로", "연남동",
    "통영 케이블카 미륵산", "담양 죽녹원", "보성 녹차밭", "양산 통도사",
]


def main():
    OUT_WK = os.path.join(ROOT, "web", "src", "data", "korea_week_places.json")
    
    # Load details if exists
    details = {}
    details_path = os.path.join(ROOT, "web", "src", "data", "korea_places_details.json")
    if os.path.exists(details_path):
        try:
            with open(details_path, "r", encoding="utf-8") as f:
                details = json.load(f)
            print(f"Loaded {len(details)} details items from {details_path}")
        except Exception as e:
            print(f"Error loading details: {e}")

    rank = {nk: i for i, nk in enumerate(POP_ORDER)}
    big = 10000
    order = sorted(range(len(P)), key=lambda i: (rank.get(P[i][0], big + i)))
    data = []
    for newpos, idx in enumerate(order, 1):
        nk, ne, reg, cat, leisure, why_ko, why_en, motif = P[idx]
        orig_no_str = str(idx + 1)
        det = details.get(orig_no_str, {})
        data.append({
            "no": newpos, "name_ko": nk, "name_en": ne,
            "region_ko": reg, "region_en": REGION_EN.get(reg, reg),
            "category": cat, "leisure_ko": leisure,
            "why_ko": why_ko, "why_en": why_en, "motif": motif,
            "week": newpos if newpos <= 24 else None,   # 상위 24 → 주별 월요일
            # Merge details
            "description_en": det.get("description_en", ""),
            "description_ko": det.get("description_ko", ""),
            "directions_en": det.get("directions_en", ""),
            "directions_ko": det.get("directions_ko", ""),
            "map_link": det.get("map_link", ""),
            "official_link": det.get("official_link", ""),
            "image_url": det.get("image_url", ""),
        })
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    # 주별 월요일 배경 매핑(상위 24)
    wk_map = [{"week": d["week"], "no": d["no"], "name_ko": d["name_ko"],
               "name_en": d["name_en"], "motif": d["motif"]} for d in data if d["week"]]
    json.dump(wk_map, open(OUT_WK, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"{len(data)} places -> {os.path.relpath(OUT, ROOT)}")
    print(f"top-24 week map -> {os.path.relpath(OUT_WK, ROOT)}")
    print("week 1-6 places:", [f"{d['week']}.{d['name_ko']}" for d in data if d["week"] and d["week"] <= 6])
    from collections import Counter
    print("by region:", dict(Counter(d["region_en"] for d in data)))


if __name__ == "__main__":
    main()
