# -*- coding: utf-8 -*-
"""W20 5개국어 자막: en.srt 타이밍 + ja/zh/es 번역('한글'[발음]은 유지, 설명·뜻만 번역).
   ko/en은 이미 있음. ja/zh/es srt를 생성. 사용: python make_w20_subs.py"""
import re, os
os.chdir(r"D:\Entertainments\DevEnvironment\autovideo")
EN = "hangeul_birth_vowels/hangeul_w20_injun_np.en.srt"

JA = [
 "こんにちは！ここはソウルの'이태원' [i-tae-won]、",
 "世界中の文化が集まる街です。今日は",
 "突然の緊急事態に韓国語で対処する方法を学びましょう！",
 "旅行中は、",
 "突然具合が悪くなったり、大切な物を'잃어버리다' [il-eo-beo-ri-da]（なくす）ことがあります。",
 "一番大切なのは'침착' [chim-chak]（冷静）でいることです。",
 "覚えておいて：緊急時は'도와주세요' [do-wa-ju-se-yo]（助けて）と言うのを恥ずかしがらないで。",
 "韓国人は喜んで助けてくれます。",
 "具合が悪いとき：'아프다' [a-peu-da]（痛い・具合が悪い）、",
 "状態を表す形容詞です。",
 "痛い所を前に：'배가 아파요' [bae-ga-a-pa-yo] — お腹が痛いです。",
 "転んだりぶつかったりしたとき：'다치다' [da-chi-da]（けがをする）、",
 "動詞です。'다리를 다쳤어요' [da-ri-reul-da-chyeot-eo-yo] — 足をけがしました。",
 "軽い症状なら、",
 "'약국' [yak-guk]（薬局）を探して — 緑の十字が目印。",
 "'약 주세요' [yak-ju-se-yo]（薬をください）と言えばOK。",
 "重いときは'병원' [byeong-won]（病院）へ。",
 "'병원에 가고 싶어요' [byeong-won-e-ga-go-sip-eo-yo] — 病院に行きたいです。",
 "火事や救急車には'119'。",
 "電話して'도와주세요' [do-wa-ju-se-yo]（助けて）と言います。",
 "犯罪や危険には'112'、警察です。",
 "'112'も'119'も24時間、無料です。",
 "物がなくなったとき：'잃어버리다' [il-eo-beo-ri-da]（なくす）、",
 "動詞で、今日の重要表現です。",
 "一番心強い一言：'도와주세요' [do-wa-ju-se-yo] — '돕다' [dop-da]（助ける）から来た丁寧な依頼です。",
 "今日の重要文型：'___을 잃어버렸어요' [_-_-_-eul-il-eo-beo-ryeot-eo-yo]（___をなくしました）。",
 "なくした物を空欄に入れます。",
 "'지갑을 잃어버렸어요' [ji-gap-eul-il-eo-beo-ryeot-eo-yo] — 財布をなくしました。",
 "物を入れ替えて：'여권' [yeo-gwon]（パスポート）、'휴대폰' [hyu-dae-pon]（携帯）。",
 "前に'도와주세요' [do-wa-ju-se-yo]を付けると切迫感が：'도와주세요,",
 "가방을 잃어버렸어요'！ — 助けて、かばんをなくしました！",
 "こう聞かれます：'어디에서 잃어버렸어요' [eo-di-e-seo-il-eo-beo-ryeot-eo-yo]？",
 "— どこでなくしましたか？",
 "'지하철에서요' [ji-ha-cheol-e-seo-yo] — 地下鉄で、と答えます。",
 "'배가 아파요' [bae-ga-a-pa-yo] — お腹が痛い；'다리를 다쳤어요' [da-ri-reul-da-chyeot-eo-yo] — 足をけがしました。",
 "痛い所を指さして。",
 "丁寧に。'실례합니다' [sil-rye-hap-ni-da]（すみません）で始めれば、",
 "初対面の人でも喜んで助けてくれます。",
 "通報するときの二つの鍵：何が起きたか、",
 "そしてどこか。この二つをはっきりと。",
 "こう聞かれます：'무슨 일이에요' [mu-seun-il-i-e-yo]？ — どうしましたか？",
 "落ち着いて説明すればOK。",
 "電話して'119죠 친구가 다쳤어요 여기는 이태원이에요' — 119ですか？",
 "友達がけがをしました。梨泰院にいます。",
 "電話して'112죠 가방을 잃어버렸어요 도와주세요' — 112ですか？",
 "かばんをなくしました。助けてください。",
 "急いでいてもゆっくりと。",
 "相手が分からなければ：'다시 말해 주세요' [da-si-mal-hae-ju-se-yo] — もう一度言ってください。",
 "場所を伝えて：'여기는 이태원역 근처예요' [yeo-gi-neun-i-tae-won-yeok-geun-cheo-ye-yo] — 梨泰院駅の近くです。",
 "ではロールプレイ。薬局で'배가 아파요' [bae-ga-a-pa-yo]、",
 "'소화제 주세요' [so-hwa-je-ju-se-yo] — お腹が痛い、消化剤を、",
 "ください。",
 "遺失物センターで：'가방을 잃어버렸어요. 도와주세요' [ga-bang-eul-il-eo-beo-ryeot-eo-yo-.-do-wa-ju-se-yo]。",
 "— かばんをなくしました。助けてください。",
 "韓国では、危機のとき助け合うのは当たり前です。",
 "'112'と'119'は通訳のサポートも受けられます。",
 "助けてもらったら'고맙습니다' [go-map-seup-ni-da] — ありがとう。",
 "小さな感謝が大きな意味を持ちます。",
 "今日は'아프다' [a-peu-da]、'다치다' [da-chi-da]、'잃어버리다' [il-eo-beo-ri-da]を学び、",
 "'___을 잃어버렸어요' [_-_-_-eul-il-eo-beo-ryeot-eo-yo]と'도와주세요' [do-wa-ju-se-yo]で助けを求め、",
 "そして'112'と'119'への通報を練習しました。",
 "どんな突発状況を経験しましたか？",
 "コメントで教えてください。",
 "役立つ韓国語でまた会いましょう — 登録といいねもお忘れなく！",
]

ZH = [
 "你好！这里是首尔的'이태원' [i-tae-won]，",
 "汇聚了世界各国文化的地方。今天，",
 "一起学习用韩语应对突发状况吧！",
 "旅行时，",
 "可能会突然身体不适，或'잃어버리다' [il-eo-beo-ri-da]（丢失）珍贵的东西。",
 "最重要的是保持'침착' [chim-chak]（冷静）。",
 "记住：紧急时不要害羞，大声说'도와주세요' [do-wa-ju-se-yo]（请帮帮我）。",
 "韩国人很乐意帮忙。",
 "身体不舒服时：'아프다' [a-peu-da]（不舒服），",
 "这是描述状态的形容词。",
 "把部位放前面：'배가 아파요' [bae-ga-a-pa-yo] — 我肚子疼。",
 "摔倒或撞到时：'다치다' [da-chi-da]（受伤），",
 "这是动词。'다리를 다쳤어요' [da-ri-reul-da-chyeot-eo-yo] — 我的腿受伤了。",
 "轻微症状时，",
 "找'약국' [yak-guk]（药店） — 寻找绿色十字标志。",
 "只需说'약 주세요' [yak-ju-se-yo]（请给我药）。",
 "严重时，去'병원' [byeong-won]（医院）。",
 "说'병원에 가고 싶어요' [byeong-won-e-ga-go-sip-eo-yo] — 我想去医院。",
 "火灾或救护车，拨打'119'。",
 "打电话说'도와주세요' [do-wa-ju-se-yo]（请帮帮我）。",
 "犯罪或危险，拨打'112'，警察。",
 "'112'和'119'都是24小时、免费的。",
 "东西不见时：'잃어버리다' [il-eo-beo-ri-da]（丢失），",
 "这是动词 — 也是今天的核心表达。",
 "最安心的一句：'도와주세요' [do-wa-ju-se-yo] — 来自'돕다' [dop-da]（帮助）的礼貌请求。",
 "今天的核心句型：'___을 잃어버렸어요' [_-_-_-eul-il-eo-beo-ryeot-eo-yo]（我丢了___）。",
 "把丢失的东西填入空格。",
 "'지갑을 잃어버렸어요' [ji-gap-eul-il-eo-beo-ryeot-eo-yo] — 我丢了钱包。",
 "替换物品：'여권' [yeo-gwon]（护照）、'휴대폰' [hyu-dae-pon]（手机）。",
 "前面加'도와주세요' [do-wa-ju-se-yo]更急迫：'도와주세요,",
 "가방을 잃어버렸어요'！ — 救命，我丢了包！",
 "他们会问：'어디에서 잃어버렸어요' [eo-di-e-seo-il-eo-beo-ryeot-eo-yo]？",
 "— 你在哪里丢的？",
 "回答'지하철에서요' [ji-ha-cheol-e-seo-yo] — 在地铁上。",
 "'배가 아파요' [bae-ga-a-pa-yo] — 肚子疼；'다리를 다쳤어요' [da-ri-reul-da-chyeot-eo-yo] — 腿受伤了。",
 "指出疼的地方。",
 "要礼貌。用'실례합니다' [sil-rye-hap-ni-da]（打扰一下）开头，",
 "连陌生人也会乐意帮忙。",
 "报警时两个要点：发生了什么，",
 "以及在哪里。把这两点说清楚。",
 "他们会问：'무슨 일이에요' [mu-seun-il-i-e-yo]？ — 发生什么事了？",
 "冷静地说明即可。",
 "打电话说'119죠 친구가 다쳤어요 여기는 이태원이에요' — 是119吗？",
 "我朋友受伤了。我们在梨泰院。",
 "打电话说'112죠 가방을 잃어버렸어요 도와주세요' — 是112吗？",
 "我丢了包。请帮帮我。",
 "再急也要慢慢说。",
 "对方听不懂时：'다시 말해 주세요' [da-si-mal-hae-ju-se-yo] — 请再说一遍。",
 "说出位置：'여기는 이태원역 근처예요' [yeo-gi-neun-i-tae-won-yeok-geun-cheo-ye-yo] — 我在梨泰院站附近。",
 "现在角色扮演。在药店说'배가 아파요' [bae-ga-a-pa-yo]，",
 "'소화제 주세요' [so-hwa-je-ju-se-yo] — 肚子疼，请给我消化药，",
 "谢谢。",
 "在失物招领处：'가방을 잃어버렸어요. 도와주세요' [ga-bang-eul-il-eo-beo-ryeot-eo-yo-.-do-wa-ju-se-yo]。",
 "— 我丢了包。请帮帮我。",
 "在韩国，危急时互相帮助是理所当然的。",
 "'112'和'119'甚至提供翻译帮助。",
 "得到帮助后说'고맙습니다' [go-map-seup-ni-da] — 谢谢。",
 "小小的谢意意义重大。",
 "今天我们学了'아프다' [a-peu-da]、'다치다' [da-chi-da]、'잃어버리다' [il-eo-beo-ri-da]，",
 "用'___을 잃어버렸어요' [_-_-_-eul-il-eo-beo-ryeot-eo-yo]和'도와주세요' [do-wa-ju-se-yo]求助，",
 "并练习了拨打'112'和'119'。",
 "你遇到过什么突发状况？",
 "在评论里告诉我们。",
 "下次再一起学实用韩语 — 别忘了订阅和点赞！",
]

ES = [
 "¡Hola! Este es el barrio '이태원' [i-tae-won] de Seúl,",
 "donde se encuentran culturas de todo el mundo. Hoy,",
 "¡aprendamos a manejar emergencias repentinas en coreano!",
 "Cuando viajas,",
 "puedes sentirte mal de repente o '잃어버리다' [il-eo-beo-ri-da] (perder) algo valioso.",
 "Lo más importante es mantener la '침착' [chim-chak] (calma).",
 "Recuerda: no te dé vergüenza decir '도와주세요' [do-wa-ju-se-yo] (ayúdame) en una emergencia.",
 "Los coreanos ayudan con gusto.",
 "Cuando te sientes mal: '아프다' [a-peu-da] (estar enfermo),",
 "un adjetivo descriptivo.",
 "Pon la parte delante: '배가 아파요' [bae-ga-a-pa-yo] — me duele el estómago.",
 "Si te caes o te golpeas: '다치다' [da-chi-da] (lastimarse),",
 "un verbo. '다리를 다쳤어요' [da-ri-reul-da-chyeot-eo-yo] — me lastimé la pierna.",
 "Para síntomas leves,",
 "busca una '약국' [yak-guk] (farmacia) — busca la cruz verde.",
 "Solo di '약 주세요' [yak-ju-se-yo] — medicina, por favor.",
 "Si es grave, ve a un '병원' [byeong-won] (hospital).",
 "Di '병원에 가고 싶어요' [byeong-won-e-ga-go-sip-eo-yo] — quiero ir al hospital.",
 "Para incendios o ambulancia, llama al '119'.",
 "Llama y di '도와주세요' [do-wa-ju-se-yo] (ayúdame).",
 "Para delitos o peligro, llama al '112', la policía.",
 "'112' y '119' son gratis, las 24 horas.",
 "Cuando algo desaparece: '잃어버리다' [il-eo-beo-ri-da] (perder),",
 "un verbo — y la expresión clave de hoy.",
 "La frase más tranquilizadora: '도와주세요' [do-wa-ju-se-yo] — una petición cortés de '돕다' [dop-da] (ayudar).",
 "El patrón clave de hoy: '___을 잃어버렸어요' [_-_-_-eul-il-eo-beo-ryeot-eo-yo] (perdí ___).",
 "Pon el objeto perdido en el espacio.",
 "'지갑을 잃어버렸어요' [ji-gap-eul-il-eo-beo-ryeot-eo-yo] — perdí mi cartera.",
 "Cambia el objeto: '여권' [yeo-gwon] (pasaporte), '휴대폰' [hyu-dae-pon] (móvil).",
 "Añade '도와주세요' [do-wa-ju-se-yo] delante para urgencia: '도와주세요,",
 "가방을 잃어버렸어요'! — ¡Ayuda, perdí mi bolso!",
 "Te preguntarán '어디에서 잃어버렸어요' [eo-di-e-seo-il-eo-beo-ryeot-eo-yo]?",
 "— ¿Dónde lo perdiste?",
 "Responde '지하철에서요' [ji-ha-cheol-e-seo-yo] — en el metro.",
 "'배가 아파요' [bae-ga-a-pa-yo] — me duele el estómago; '다리를 다쳤어요' [da-ri-reul-da-chyeot-eo-yo] — me lastimé la pierna.",
 "Señala dónde te duele.",
 "Sé cortés. Empieza con '실례합니다' [sil-rye-hap-ni-da] (disculpe),",
 "y hasta los desconocidos ayudarán con gusto.",
 "Al reportar, dos claves: qué pasó,",
 "y dónde. Solo sé claro con esos dos.",
 "Preguntarán '무슨 일이에요' [mu-seun-il-i-e-yo]? — ¿Qué pasó?",
 "Solo explica con calma.",
 "Llama y di '119죠 친구가 다쳤어요 여기는 이태원이에요' — ¿Es el 119?",
 "Mi amigo está herido. Estamos en Itaewon.",
 "Llama y di '112죠 가방을 잃어버렸어요 도와주세요' — ¿Es el 112?",
 "Perdí mi bolso. Por favor, ayúdenme.",
 "Aunque tengas prisa, ve despacio.",
 "Si no entienden: '다시 말해 주세요' [da-si-mal-hae-ju-se-yo] — repítalo, por favor.",
 "Da tu ubicación: '여기는 이태원역 근처예요' [yeo-gi-neun-i-tae-won-yeok-geun-cheo-ye-yo] — estoy cerca de la estación de Itaewon.",
 "Ahora un juego de rol. En la farmacia, di '배가 아파요' [bae-ga-a-pa-yo],",
 "'소화제 주세요' [so-hwa-je-ju-se-yo] — me duele el estómago; medicina digestiva,",
 "por favor.",
 "En objetos perdidos: '가방을 잃어버렸어요. 도와주세요' [ga-bang-eul-il-eo-beo-ryeot-eo-yo-.-do-wa-ju-se-yo].",
 "— Perdí mi bolso. Por favor, ayúdenme.",
 "En Corea, ayudar en una crisis es natural.",
 "'112' y '119' incluso ofrecen ayuda de intérprete.",
 "Después de recibir ayuda, di '고맙습니다' [go-map-seup-ni-da] — gracias.",
 "Un pequeño gracias significa mucho.",
 "Hoy aprendimos '아프다' [a-peu-da], '다치다' [da-chi-da], '잃어버리다' [il-eo-beo-ri-da],",
 "pedimos ayuda con '___을 잃어버렸어요' [_-_-_-eul-il-eo-beo-ryeot-eo-yo] y '도와주세요' [do-wa-ju-se-yo],",
 "y practicamos llamar al '112' y al '119'.",
 "¿Qué emergencias has enfrentado?",
 "Cuéntanos en los comentarios.",
 "¡Nos vemos de nuevo con coreano útil — y no olvides suscribirte y dar like!",
]

# en.srt에서 타임코드 파싱
blocks = [b for b in open(EN, encoding="utf-8").read().split("\n\n") if b.strip()]
times = []
for b in blocks:
    for ln in b.splitlines():
        if "-->" in ln:
            times.append(ln.strip()); break
n = len(times)
assert len(JA) == len(ZH) == len(ES) == n, f"큐 수 불일치: en={n} ja={len(JA)} zh={len(ZH)} es={len(ES)}"


def write_srt(texts, path):
    with open(path, "w", encoding="utf-8") as f:
        for i, (tc, tx) in enumerate(zip(times, texts), 1):
            f.write(f"{i}\n{tc}\n{tx}\n\n")
    print(f"{path}  ({n}큐)")


P = "hangeul_birth_vowels/w20pkg"
write_srt(JA, f"{P}/hangeul_w20_injun_np.ja.srt")
write_srt(ZH, f"{P}/hangeul_w20_injun_np.zh.srt")
write_srt(ES, f"{P}/hangeul_w20_injun_np.es.srt")
