#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""make_lessons168.py — 24개 주제 × 7일 = 168강 커리큘럼 생성 → web/src/data/lessons168.json.

설계 원칙
- Day1(▶ 핵심 영상) = 기존 24강 핵심 영상(앵커, 재사용). 기존 영상이 다루는 '핵심 개념'.
- Day2~7 = 그 핵심을 둘러싼 '다른 일일 스킬'(어휘/문형/듣기/말하기/문화/복습). 기존 24강과 비중복.
- 모든 일일 강의 제목·설명은 템플릿이 아니라 주차별 실제 학습 내용(어휘 목록·문법형·상황)으로 구체화.
- 근거: NotebookLM 한글교육 노트북(TTMIK Level 1, 서강 한국어 1A, 세종학당 한국어 1·2,
  국립국어원 표준 교육과정/어문규범, 해외 공영방송(BBC) 벤치마킹 24주 설계 보고서).
- 패턴 참조: BBC Learning English(짧은 일일 다기능 강의) + 일본어 교재(겐키/민나, 나선형 복습).

재실행: python make_lessons168.py
"""
import os
import json
import sqlite3

ROOT = os.path.dirname(os.path.abspath(__file__))
DB = os.path.join(ROOT, "channel", "content.db")
OUT = os.path.join(ROOT, "web", "src", "data", "lessons168.json")

LEVEL_KO = {"beginner": "초급", "intermediate": "중급", "advanced": "고급"}

# 주차별: 짧은 주제(ko/en) + 6일차 '문화' 강의 제목(ko/en) + 문화 설명(ko/en)
W = {
    1:  ("단모음", "Simple Vowels", "한글을 만든 세종대왕 이야기", "King Sejong & the Birth of Hangeul",
         "세종대왕이 백성을 위해 한글을 만든 이야기와 천지인(·ㅡㅣ) 철학을 만나요.",
         "Meet King Sejong's story and the Cheon-Ji-In (·ㅡㅣ) philosophy behind Hangeul."),
    2:  ("기초 자음", "Basic Consonants", "소리를 본뜬 글자, 한글의 과학", "Letters shaped like sounds",
         "자음이 발음 기관 모양을 본떠 만들어진 과학적 원리를 알아봐요.",
         "Discover how consonants were shaped after the speech organs that make them."),
    3:  ("거센소리·된소리", "Aspirated & Tense", "한국어 소리의 3중 세기 체계", "Korea's three-way sound strength",
         "평음·격음·경음으로 세기를 나누는 한국어만의 소리 체계를 느껴봐요.",
         "Feel Korean's unique three-way strength: plain, aspirated, tense."),
    4:  ("받침", "Batchim", "받침이 만드는 한국어의 리듬", "How batchim gives Korean its rhythm",
         "음절 맨 아래 받침이 한국어 특유의 또렷한 끝소리 리듬을 만들어요.",
         "The bottom batchim gives Korean its crisp, rhythmic syllable endings."),
    5:  ("이중모음", "Double Vowels", "입 모양이 미끄러지는 소리", "Sounds that glide",
         "반모음이 미끄러지며 만들어지는 이중모음의 입 모양 변화를 봐요.",
         "Watch the mouth glide as semivowels form Korea's double vowels."),
    6:  ("연음·소리규칙", "Liaison & Sound Rules", "쓰는 대로 ≠ 읽는 대로", "Spelled vs spoken",
         "받침이 뒤 모음으로 넘어가는 연음 등, 쓰기와 읽기가 다른 이유를 배워요.",
         "Learn why spelling and pronunciation differ — liaison and sound rules."),
    7:  ("인사·자기소개", "Greetings", "한국의 인사 예절과 고개 숙이기", "Korean greeting etiquette & bowing",
         "상황과 상대에 따라 달라지는 한국의 인사 예절과 고개 숙임을 익혀요.",
         "Learn Korean bowing and greetings that change with person and setting."),
    8:  ("숫자·시간", "Numbers & Time", "두 숫자 체계와 나이 문화", "Two number systems & age culture",
         "고유어·한자어 두 숫자 체계와 나이를 중시하는 한국 문화를 알아봐요.",
         "Two number systems and why age matters so much in Korea."),
    9:  ("동네·위치", "Neighborhood", "한국 동네 풍경과 편의시설", "Korean neighborhoods & amenities",
         "골목·편의점·동네 풍경 등 한국의 생활권 문화를 둘러봐요.",
         "Tour Korean neighborhoods: alleys, convenience stores, and daily amenities."),
    10: ("쇼핑·가격", "Shopping", "시장과 마트, 그리고 흥정 문화", "Markets, marts & bargaining",
         "전통시장과 대형마트, 가벼운 흥정이 오가는 한국 쇼핑 문화를 봐요.",
         "Traditional markets, marts, and the friendly art of bargaining."),
    11: ("식당·맛", "Dining", "식당 예절과 반찬 문화", "Dining etiquette & banchan",
         "무료 반찬, 함께 나눠 먹기 등 한국 식당의 따뜻한 식문화를 익혀요.",
         "Free banchan and sharing — the warmth of Korean dining culture."),
    12: ("교통·환승", "Transport", "교통카드 T-money와 환승 할인", "T-money & transfer discounts",
         "T-money 한 장으로 버스·지하철을 환승 할인받는 한국 교통 문화를 배워요.",
         "One T-money card, free transfers — Korea's smart transit culture."),
    13: ("길 찾기", "Directions", "한국의 주소와 길 안내 방식", "Korean addresses & wayfinding",
         "도로명 주소와 친절한 길 안내 등 한국에서 길 찾는 법을 익혀요.",
         "Road-name addresses and how Koreans give friendly directions."),
    14: ("하루 일과", "Daily Routine", "한국인의 하루를 들여다보기", "A day in Korean life",
         "아침부터 밤까지, 한국인의 평범한 하루 흐름을 들여다봐요.",
         "Peek into an ordinary Korean day, from morning to night."),
    15: ("날씨·계절", "Weather & Seasons", "뚜렷한 사계절과 절기 문화", "Four seasons & solar terms",
         "뚜렷한 사계절과 절기(입춘·장마·단풍 등) 문화를 한국어로 만나요.",
         "Korea's vivid four seasons and traditional solar-term culture."),
    16: ("취미·빈도", "Hobbies", "한국의 여가와 동호회 문화", "Korean leisure & clubs",
         "등산·PC방·동호회 등 한국인이 즐기는 여가와 모임 문화를 봐요.",
         "Hiking, PC bangs, hobby clubs — how Koreans spend their free time."),
    17: ("K-컬처·구어", "K-Culture", "K-드라마·K-팝 속 진짜 말투", "Real speech in K-drama & K-pop",
         "드라마·예능 속 반말과 줄임말, 진짜 살아있는 구어체를 들어봐요.",
         "Catch the real casual speech and slang of K-drama and K-pop."),
    18: ("감정 표현", "Emotions", "한국의 '정(情)' 문화", "The Korean culture of 'jeong'",
         "말로 다 못하는 한국의 '정(情)'과 섬세한 감정 표현을 느껴봐요.",
         "Feel 'jeong' — the deep, unspoken warmth in Korean emotion."),
    19: ("의견·설득", "Opinions", "한국의 토론과 의견 나누기", "Discussion culture in Korea",
         "근거를 들어 정중히 의견을 나누는 한국의 토론 문화를 배워요.",
         "How Koreans share opinions politely, with reasons, in discussion."),
    20: ("돌발 상황", "Emergencies", "긴급 전화 112·119와 도움 요청", "Emergency numbers 112 & 119",
         "112·119 신고와 약국·병원 이용 등 위급할 때 도움받는 법을 익혀요.",
         "Calling 112/119 and getting help at pharmacies and clinics."),
    21: ("인물 묘사", "Describing People", "호칭과 예절, 첫인상 표현", "Titles, etiquette & first impressions",
         "나이·관계에 따른 호칭과 첫인상을 표현하는 한국식 예절을 배워요.",
         "Titles by age and relationship, and how Koreans describe first impressions."),
    22: ("여행·계획", "Travel & Plans", "한국의 명소와 여행 문화", "Korea's sights & travel culture",
         "경복궁·제주도 등 명소와 한국인의 여행·휴가 문화를 만나요.",
         "Gyeongbokgung, Jeju, and how Koreans love to travel."),
    23: ("모임·약속", "Social Planning", "회식과 모임, 약속 조율 문화", "Group dining & making plans",
         "회식·모임을 잡고 시간을 맞추는 한국의 약속 문화를 익혀요.",
         "Setting up hoesik and meetups — Korea's culture of making plans."),
    24: ("마무리·수료", "Wrap-up", "수료, 그리고 다음 단계로", "Completion & your next steps",
         "24주의 여정을 돌아보고 TOPIK·세종한국어평가 등 다음 단계를 그려봐요.",
         "Reflect on 24 weeks and map your next steps: TOPIK, SKA, and beyond."),
}

# 7일 스킬 슬롯 (icon, skill_ko, skill_en)
SLOT = [
    ("▶",  "핵심 영상", "Core Video"),
    ("📚", "어휘", "Vocabulary"),
    ("🧩", "문형", "Patterns"),
    ("👂", "듣기", "Listening"),
    ("🗣️", "말하기", "Speaking"),
    ("🌏", "문화", "Culture"),
    ("🎮", "복습", "Review"),
]

# 주차별 일일 강의 상세 — 각 항목: (title_ko, title_en, desc_ko, desc_en)
# 순서: vocab(Day2) / pattern(Day3) / listen(Day4) / speak(Day5) / review(Day7)
# (Day1 핵심영상=DB 앵커, Day6 문화=W 위 데이터 사용)
D = {
 1: [  # 단모음
   ("모음만으로 만드는 첫 단어", "First Words from Vowels Alone",
    "‘아이·오이·우유·이·오’처럼 모음만으로 이루어진 쉬운 첫 단어를 그림과 소리로 익혀요.",
    "Learn easy first words made of vowels only — 아이, 오이, 우유 — with pictures and sound."),
   ("ㅇ + 모음으로 음절 만들기", "Building Syllables with ㅇ + Vowel",
    "소리 없는 ㅇ에 모음을 붙여 ‘아 어 오 우 으 이’ 음절 블록을 만드는 규칙을 배워요.",
    "Add a silent ㅇ to each vowel to build the syllable blocks 아 어 오 우 으 이."),
   ("비슷한 모음 구별해 듣기", "Hearing Vowels Apart",
    "ㅗ/ㅜ, ㅐ/ㅔ, ㅏ/ㅓ처럼 헷갈리는 모음 짝을 듣고 구별하는 귀를 길러요.",
    "Train your ear on tricky pairs: ㅗ vs ㅜ, ㅐ vs ㅔ, ㅏ vs ㅓ."),
   ("입 모양 따라 8모음 소리 내기", "8 Vowels — Mouth Shapes",
    "거울을 보며 8개 단모음의 입 모양을 따라 또박또박 소리 내어 읽어요.",
    "Mirror the mouth shapes and pronounce all 8 simple vowels clearly."),
   ("모음 빙고 & 짝 맞추기", "Vowel Bingo & Matching",
    "퀴즈와 빙고로 단모음 8개를 즐겁게 복습하고 한 주를 마무리해요.",
    "Wrap up the week with vowel bingo and matching — review all 8 vowels."),
 ],
 2: [  # 기초 자음 + 모아쓰기
   ("첫 자음 단어: 가·나·다·바나나", "First Consonant Words",
    "‘가방·나비·다리·머리·바나나·사자’처럼 기초 자음으로 만든 첫 단어를 익혀요.",
    "Build first words with basic consonants: 가방, 나비, 다리, 머리, 바나나, 사자."),
   ("초성+중성 모아쓰기", "Stacking Consonant + Vowel",
    "자음과 모음을 한 칸에 모아 ‘가 나 다 라…’ 음절 블록을 쌓는 모아쓰기를 배워요.",
    "Stack a consonant and vowel into one block: 가 나 다 라 — Korean syllable building."),
   ("자음 첫소리 구별해 듣기", "Hearing Initial Consonants",
    "ㄱ/ㄴ/ㄷ/ㅁ/ㅂ 등 단어의 첫 자음 소리를 듣고 구별하는 연습을 해요.",
    "Listen and tell apart initial consonants: ㄱ, ㄴ, ㄷ, ㅁ, ㅂ and more."),
   ("‘가나다라’ 또박또박 읽기", "Reading 가나다라 Aloud",
    "가나다 노래에 맞춰 자음 10개를 또박또박 소리 내어 읽어요.",
    "Sing along to 가나다 and read all 10 consonants out loud."),
   ("자음 카드 뒤집기 게임", "Consonant Card Flip Game",
    "카드 뒤집기 게임으로 기초 자음 10개를 재미있게 복습해요.",
    "Flip cards to review the 10 basic consonants — the fun way."),
 ],
 3: [  # 거센/된소리
   ("거센·된소리 단어: 코·토끼·빵", "Aspirated & Tense Words",
    "‘코·키·토끼·까치·빵·짜장’처럼 거센소리·된소리가 든 단어를 익혀요.",
    "Words with aspirated/tense sounds: 코, 토끼, 까치, 빵, 짜장."),
   ("평음–격음–경음 3중 대립", "Plain–Aspirated–Tense Trio",
    "‘가–카–까’처럼 같은 자리에서 세기만 달라지는 3중 짝을 만들어 봐요.",
    "Build the trio 가–카–까: same place, three strengths."),
   ("최소대립쌍 듣고 고르기", "Minimal Pairs by Ear",
    "‘달–탈–딸’ 같은 최소대립쌍을 듣고 어느 소리인지 골라내요.",
    "Hear minimal pairs like 달–탈–딸 and pick the right one."),
   ("숨과 긴장으로 소리 내기", "Breath & Tension Practice",
    "거센소리는 숨을 내쉬고 된소리는 목을 긴장시켜 정확히 소리 내요.",
    "Push breath for aspirated, tense the throat for tense consonants."),
   ("3단 세기 분류 게임", "Three-Strength Sorting Game",
    "단어를 평음·격음·경음 세 칸으로 분류하는 게임으로 복습해요.",
    "Sort words into plain / aspirated / tense — a review game."),
 ],
 4: [  # 받침/대표7음
   ("받침 단어: 산·문·밥·꽃", "Batchim Words",
    "‘산·문·밥·국·꽃·옷·강’처럼 받침이 있는 단어를 그림으로 익혀요.",
    "Words with batchim: 산, 문, 밥, 국, 꽃, 옷, 강 — with pictures."),
   ("대표 7음으로 끝소리 정리", "7 Representative Endings",
    "여러 받침이 ㄱㄴㄷㄹㅁㅂㅇ 7개 대표음으로 발음되는 규칙을 배워요.",
    "Learn how many batchim collapse into 7 sounds: ㄱㄴㄷㄹㅁㅂㅇ."),
   ("받침 7대표음 구별해 듣기", "Hearing the 7 Endings",
    "받침 소리만 듣고 7대표음 중 어느 끝소리인지 구별해요.",
    "Listen to endings and identify which of the 7 sounds it is."),
   ("받침 끝소리 또렷이 말하기", "Crisp Final Sounds",
    "받침을 가볍게 닫아 ‘밥·꽃·옷’의 끝소리를 또렷이 발음해요.",
    "Close each batchim lightly to pronounce 밥, 꽃, 옷 crisply."),
   ("받침 분류 짝 맞추기", "Batchim Matching Game",
    "단어와 대표 받침음을 짝지어 맞추는 게임으로 복습해요.",
    "Match words to their representative ending sound — review game."),
 ],
 5: [  # 이중모음
   ("이중모음 단어: 야구·여우·과자", "Double-Vowel Words",
    "‘야구·여우·요리·과자·왜·의자’처럼 이중모음이 든 단어를 익혀요.",
    "Words with double vowels: 야구, 여우, 요리, 과자, 왜, 의자."),
   ("반모음 + 단모음 = 이중모음", "Semivowel + Vowel",
    "‘ㅣ+ㅏ=ㅑ, ㅗ+ㅏ=ㅘ’처럼 반모음이 미끄러져 이중모음이 되는 원리를 배워요.",
    "ㅣ+ㅏ=ㅑ, ㅗ+ㅏ=ㅘ — how a glide forms a double vowel."),
   ("이중모음 vs 단모음 듣기", "Double vs Simple by Ear",
    "‘아/야, 오/요’처럼 단모음과 이중모음을 듣고 구별해요.",
    "Tell 아/야 and 오/요 apart — simple vs double vowels."),
   ("입 모양 미끄러뜨려 말하기", "Gliding the Mouth Shape",
    "한 모음에서 다음 모음으로 입을 미끄러뜨리며 이중모음을 소리 내요.",
    "Glide your mouth from one vowel to the next to sound double vowels."),
   ("이중모음 만들기 퍼즐", "Double-Vowel Puzzle",
    "반모음과 단모음 조각을 맞춰 이중모음을 만드는 퍼즐로 복습해요.",
    "Assemble glide + vowel pieces into double vowels — a review puzzle."),
 ],
 6: [  # 연음/소리규칙
   ("연음되는 단어: 꽃이·옷을·집에", "Words That Link",
    "‘꽃이·옷을·집에·음식’처럼 받침이 뒤 모음과 이어지는 단어를 익혀요.",
    "Words where batchim links to the next vowel: 꽃이, 옷을, 집에."),
   ("받침+모음 연음 규칙", "Liaison Rule",
    "‘꽃이→[꼬치]’처럼 받침이 뒤 모음으로 넘어가 소리 나는 연음을 배워요.",
    "꽃이 → [꼬치]: how a batchim moves onto the next vowel."),
   ("표기 vs 발음 받아쓰기", "Spelling vs Sound Dictation",
    "들리는 발음과 실제 표기가 다른 단어를 듣고 바르게 받아써요.",
    "Hear the spoken form, then write the correct spelling."),
   ("자연스럽게 이어 읽기", "Smooth Linked Reading",
    "받침과 모음을 끊지 않고 자연스럽게 이어 읽는 연습을 해요.",
    "Read smoothly, linking batchim into the following vowel."),
   ("연음 변환 퀴즈", "Liaison Quiz",
    "표기형을 보고 실제 발음을 맞히는 퀴즈로 소리 규칙을 복습해요.",
    "See the spelling, guess the pronunciation — a sound-rule quiz."),
 ],
 7: [  # 인사·자기소개
   ("첫 만남 필수 인사말", "Must-Know Greetings",
    "‘안녕하세요·감사합니다·만나서 반갑습니다’ 등 첫 만남 인사말을 익혀요.",
    "Essential first-meeting phrases: 안녕하세요, 감사합니다, 만나서 반갑습니다."),
   ("‘저는 ___이에요/예요’", "I am ___ (이에요/예요)",
    "이름·나라를 넣어 ‘저는 ___이에요/예요’로 나를 소개하는 문형을 배워요.",
    "Introduce yourself with 저는 ___이에요/예요 — name and country."),
   ("자기소개 대화 듣기", "Listening: Introductions",
    "두 사람이 처음 만나 인사하는 대화를 듣고 이름·나라 정보를 잡아요.",
    "Hear two people meet, and catch their names and countries."),
   ("내 소개 30초 역할극", "30-Second Self-Intro Roleplay",
    "배운 표현으로 이름·나라·인사를 담아 30초 자기소개를 직접 말해 봐요.",
    "Roleplay a 30-second self-introduction using what you learned."),
   ("인사·소개 미션 게임", "Greeting Mission Game",
    "상황 카드를 뽑아 알맞은 인사를 고르는 미션 게임으로 복습해요.",
    "Draw situation cards and pick the right greeting — a mission game."),
 ],
 8: [  # 숫자·시간
   ("두 숫자 체계: 하나~열 / 일~십", "Two Number Systems",
    "고유어(하나~열)와 한자어(일~십) 두 숫자 체계와 ‘시·분·요일’ 어휘를 익혀요.",
    "Native (하나~열) and Sino (일~십) numbers, plus hour/minute/weekday words."),
   ("‘지금 ___시 ___분이에요’", "Telling the Time",
    "고유어+한자어를 섞어 ‘지금 세 시 삼십 분이에요’로 시간을 말해요.",
    "Mix both systems: 지금 세 시 삼십 분이에요 — telling the time."),
   ("시간·전화번호 듣기", "Listening: Times & Numbers",
    "시간, 전화번호, 가격을 듣고 숫자를 정확히 받아쓰는 연습을 해요.",
    "Catch times, phone numbers, and prices by ear and write them down."),
   ("시간·약속 말하기 역할극", "Time & Appointments Roleplay",
    "‘몇 시에 만나요?’처럼 시간과 약속을 묻고 답하는 역할극을 해요.",
    "Roleplay asking and giving times: 몇 시에 만나요?"),
   ("숫자·시간 빙고", "Numbers & Time Bingo",
    "숫자와 시간을 듣고 칸을 채우는 빙고로 한 주를 복습해요.",
    "Fill the board as you hear numbers and times — review bingo."),
 ],
 9: [  # 동네·위치
   ("동네 장소 & 위치어", "Places & Position Words",
    "‘마트·학교·은행·병원’과 ‘위·아래·앞·뒤·옆’ 위치 어휘를 익혀요.",
    "Places (마트, 학교, 은행, 병원) and positions (위, 아래, 앞, 뒤, 옆)."),
   ("‘___이/가 ___에 있어요’", "___ is at ___ (있어요)",
    "‘은행이 병원 옆에 있어요’처럼 사물·장소의 위치를 말하는 문형을 배워요.",
    "Say where things are: 은행이 병원 옆에 있어요."),
   ("위치 설명 듣기", "Listening: Locations",
    "동네 안내 대화를 듣고 어디에 무엇이 있는지 위치를 파악해요.",
    "Hear a neighborhood guide and map out what is where."),
   ("우리 동네 소개 역할극", "My Neighborhood Roleplay",
    "내 동네의 장소와 위치를 소개하는 역할극으로 직접 말해 봐요.",
    "Roleplay introducing places and locations in your neighborhood."),
   ("위치 표현 지도 게임", "Map Location Game",
    "설명을 듣고 지도에 장소를 놓는 게임으로 위치 표현을 복습해요.",
    "Place spots on a map from descriptions — a location review game."),
 ],
 10: [  # 쇼핑·가격
   ("쇼핑 어휘: 개·원·할인", "Shopping Words",
    "‘이거·저거·개·원·할인·주세요’ 등 쇼핑에 꼭 필요한 어휘를 익혀요.",
    "Shopping essentials: 이거, 저거, 개, 원, 할인, 주세요."),
   ("‘이거 얼마예요? / ___ 주세요’", "How Much? / Please Give Me",
    "‘이거 얼마예요?’로 가격을 묻고 ‘___ 주세요’로 사는 문형을 배워요.",
    "Ask 이거 얼마예요? and buy with ___ 주세요."),
   ("가격·수량 듣기", "Listening: Prices & Amounts",
    "점원의 말에서 가격과 수량을 듣고 정확히 받아쓰는 연습을 해요.",
    "Catch prices and quantities from a clerk and note them down."),
   ("시장 흥정 역할극", "Market Bargaining Roleplay",
    "‘좀 깎아 주세요’처럼 가볍게 흥정하며 물건을 사는 역할극을 해요.",
    "Roleplay buying and gently bargaining: 좀 깎아 주세요."),
   ("쇼핑 미션 게임", "Shopping Mission Game",
    "예산 안에서 물건을 사는 미션 게임으로 쇼핑 표현을 복습해요.",
    "Shop within a budget — a mission game to review shopping phrases."),
 ],
 11: [  # 식당·맛
   ("식당 어휘 & 맛 표현", "Dining & Taste Words",
    "‘메뉴·주문·계산서·포장’과 ‘맛있어요·매워요·짜요’ 맛 표현을 익혀요.",
    "Dining words (메뉴, 주문, 계산서) and tastes (맛있어요, 매워요, 짜요)."),
   ("‘___ 주세요 / ___이 맛있어요’", "Ordering & Describing Taste",
    "‘비빔밥 주세요’로 주문하고 ‘이게 맛있어요’로 맛을 말하는 문형을 배워요.",
    "Order with ___ 주세요 and describe taste with ___이 맛있어요."),
   ("식당 주문 대화 듣기", "Listening: At a Restaurant",
    "손님과 종업원의 주문 대화를 듣고 메뉴와 요청을 파악해요.",
    "Hear a customer order and catch the menu and requests."),
   ("식당 주문 역할극", "Restaurant Roleplay",
    "메뉴를 고르고 주문·계산·포장까지 해보는 식당 역할극을 해요.",
    "Roleplay the whole meal: order, pay, and ask to pack leftovers."),
   ("맛 표현 매칭 게임", "Taste Matching Game",
    "음식과 맛 표현을 짝짓는 게임으로 식당 표현을 복습해요.",
    "Match foods to taste words — a dining review game."),
 ],
 12: [  # 교통·환승
   ("교통 어휘: 타다·내리다·환승", "Transport Words",
    "‘버스·지하철·역·교통카드’와 ‘타다·내리다·환승하다’ 어휘를 익혀요.",
    "Transit words: 버스, 지하철, 역, 교통카드, 타다, 내리다, 환승하다."),
   ("‘___에서 ___까지 어떻게 가요?’", "From ___ to ___",
    "‘여기에서 강남까지 어떻게 가요?’로 길과 교통편을 묻는 문형을 배워요.",
    "Ask routes: 여기에서 강남까지 어떻게 가요?"),
   ("노선·환승 안내 듣기", "Listening: Transit Announcements",
    "지하철 안내 방송을 듣고 환승역과 내릴 곳을 파악하는 연습을 해요.",
    "Hear subway announcements and find transfer and exit stops."),
   ("길·교통 묻기 역할극", "Asking Directions Roleplay",
    "‘몇 번 버스를 타요?’처럼 교통편을 묻고 답하는 역할극을 해요.",
    "Roleplay asking transit: 몇 번 버스를 타요?"),
   ("노선도 게임", "Subway Map Game",
    "출발지에서 목적지까지 환승하며 가는 노선도 게임으로 복습해요.",
    "Navigate a subway map with transfers — a review game."),
 ],
 13: [  # 길찾기
   ("방향 어휘: 오른쪽·왼쪽·직진", "Direction Words",
    "‘오른쪽·왼쪽·직진·건너편·사거리·모퉁이’ 등 길 안내 어휘를 익혀요.",
    "Direction words: 오른쪽, 왼쪽, 직진, 건너편, 사거리, 모퉁이."),
   ("‘___까지 어떻게 가요?’ + 안내", "Asking & Giving Directions",
    "길을 묻고 ‘오른쪽으로 가세요·쭉 직진하세요’로 안내하는 문형을 배워요.",
    "Ask the way, then guide: 오른쪽으로 가세요, 쭉 직진하세요."),
   ("길 안내 듣고 지도에 표시", "Listening: Follow the Route",
    "길 안내를 듣고 지도에 경로를 따라 표시하는 연습을 해요.",
    "Listen to directions and trace the route on a map."),
   ("길 묻고 답하기 역할극", "Asking the Way Roleplay",
    "길을 잃은 상황에서 행인에게 묻고 안내받는 역할극을 해요.",
    "Roleplay getting lost and asking a passerby for directions."),
   ("길 찾기 미로 게임", "Wayfinding Maze Game",
    "안내를 따라 미로를 빠져나가는 게임으로 방향 표현을 복습해요.",
    "Escape a maze by following directions — a wayfinding game."),
 ],
 14: [  # 하루일과
   ("일과 동사: 일어나다·씻다·자다", "Daily-Routine Verbs",
    "‘일어나다·씻다·먹다·일하다·공부하다·쉬다·자다’ 일과 동사를 익혀요.",
    "Routine verbs: 일어나다, 씻다, 먹다, 일하다, 공부하다, 쉬다, 자다."),
   ("‘___고, ___아요/어요’ 순서 잇기", "Linking Actions with -고",
    "‘일어나고 씻어요’처럼 -고로 행동을 순서대로 잇는 문형을 배워요.",
    "Link actions in order with -고: 일어나고 씻어요."),
   ("하루 일과 이야기 듣기", "Listening: Someone's Day",
    "누군가의 하루 일과 이야기를 듣고 시간 순서대로 정리해요.",
    "Hear someone describe their day and order the events by time."),
   ("내 하루 말하기", "Talk About Your Day",
    "아침부터 밤까지 내 하루 일과를 순서대로 말하는 연습을 해요.",
    "Describe your own day in order, from morning to night."),
   ("일과 순서 배열 게임", "Routine-Order Game",
    "뒤섞인 일과 카드를 시간순으로 배열하는 게임으로 복습해요.",
    "Arrange shuffled routine cards in time order — a review game."),
 ],
 15: [  # 날씨·계절
   ("날씨·계절 어휘", "Weather & Season Words",
    "‘맑다·흐리다·비·눈·덥다·춥다’와 ‘봄·여름·가을·겨울’을 익혀요.",
    "Weather (맑다, 흐리다, 비, 눈, 덥다, 춥다) and the four seasons."),
   ("‘오늘 날씨가 ___아요/어요’", "Today's Weather Is ___",
    "‘오늘 날씨가 더워요’처럼 날씨와 계절을 형용사로 말하는 문형을 배워요.",
    "Describe weather with adjectives: 오늘 날씨가 더워요."),
   ("일기예보 듣기", "Listening: Weather Forecast",
    "짧은 일기예보를 듣고 오늘·내일 날씨와 기온을 파악해요.",
    "Hear a short forecast and catch today's and tomorrow's weather."),
   ("날씨·계절 이야기 역할극", "Weather & Seasons Roleplay",
    "‘이 계절을 좋아해요?’처럼 날씨와 좋아하는 계절을 이야기해요.",
    "Roleplay chatting about weather and your favorite season."),
   ("날씨 표현 짝 맞추기", "Weather Matching Game",
    "날씨 그림과 표현을 짝짓는 게임으로 한 주를 복습해요.",
    "Match weather pictures to phrases — a review game."),
 ],
 16: [  # 취미·빈도
   ("취미 어휘 & 빈도 부사", "Hobby & Frequency Words",
    "‘영화·운동·요리·독서·게임’과 ‘자주·가끔·매일’ 빈도 부사를 익혀요.",
    "Hobbies (영화, 운동, 요리, 독서) and frequency (자주, 가끔, 매일)."),
   ("‘저는 ___을/를 좋아해요’ + 빈도", "I Like ___ + How Often",
    "‘저는 영화를 좋아해요·자주 봐요’처럼 취미와 빈도를 말하는 문형을 배워요.",
    "Say what you like and how often: 저는 영화를 좋아해요, 자주 봐요."),
   ("취미 인터뷰 듣기", "Listening: Hobby Interview",
    "취미를 묻는 인터뷰를 듣고 누가 무엇을 얼마나 자주 하는지 파악해요.",
    "Hear a hobby interview and catch who does what, how often."),
   ("취미 묻고 답하기 역할극", "Hobbies Q&A Roleplay",
    "‘취미가 뭐예요?’처럼 서로 취미와 빈도를 묻고 답하는 역할극을 해요.",
    "Roleplay asking each other 취미가 뭐예요? and how often."),
   ("빈도 표현 게임", "Frequency Game",
    "행동과 빈도를 연결하는 게임으로 취미·빈도 표현을 복습해요.",
    "Match actions to frequencies — a hobbies review game."),
 ],
 17: [  # K컬처·구어
   ("구어체·신조어 어휘", "Casual & Slang Words",
    "‘반말·존댓말·줄임말’과 ‘진짜·대박·완전’ 같은 살아있는 구어 표현을 익혀요.",
    "Casual speech terms and real slang: 진짜, 대박, 완전, 줄임말."),
   ("존댓말 ↔ 반말 바꾸기", "Polite ↔ Casual Switch",
    "‘했어요 → 했어’처럼 존댓말과 반말을 상황에 맞게 바꾸는 법을 배워요.",
    "Switch between polite and casual: 했어요 → 했어."),
   ("K-드라마 대사 듣기", "Listening: K-Drama Lines",
    "드라마·예능의 짧은 대사를 듣고 구어체 표현의 뜻을 파악해요.",
    "Hear short drama lines and decode the casual expressions."),
   ("반말/존댓말 전환 역할극", "Register-Switch Roleplay",
    "친구와 윗사람에게 같은 말을 반말·존댓말로 바꿔 말하는 역할극을 해요.",
    "Roleplay the same line in casual and polite to friend vs senior."),
   ("구어 표현 퀴즈", "Slang Quiz",
    "구어·신조어의 뜻을 맞히는 퀴즈로 K-컬처 표현을 복습해요.",
    "Guess the meaning of slang — a K-culture review quiz."),
 ],
 18: [  # 감정
   ("감정 어휘: 기쁘다·속상하다", "Emotion Words",
    "‘기쁘다·슬프다·화나다·걱정되다·속상하다·설레다’ 감정 어휘를 익혀요.",
    "Emotion words: 기쁘다, 슬프다, 화나다, 걱정되다, 속상하다, 설레다."),
   ("‘___아서/어서 ___아요’ 감정 원인", "Cause of Feeling (-아서/어서)",
    "‘시험이 끝나서 기뻐요’처럼 감정의 원인을 잇는 문형을 배워요.",
    "Link feeling to cause: 시험이 끝나서 기뻐요 (-아서/어서)."),
   ("감정 대화 듣기", "Listening: Feelings",
    "친구의 고민 대화를 듣고 어떤 감정을 느끼는지 파악해요.",
    "Hear a friend share worries and identify their feelings."),
   ("공감·위로 역할극", "Empathy & Comfort Roleplay",
    "‘많이 속상했겠어요’처럼 공감하고 위로하는 역할극을 해요.",
    "Roleplay comforting: 많이 속상했겠어요."),
   ("감정 뉘앙스 매칭", "Emotion Nuance Matching",
    "비슷한 감정어의 미묘한 차이를 짝짓는 게임으로 복습해요.",
    "Match subtle differences between similar emotion words."),
 ],
 19: [  # 의견·설득
   ("의견 표현 어휘", "Opinion Words",
    "‘제 생각에는·왜냐하면·동의하다·반대하다’ 의견 어휘를 익혀요.",
    "Opinion words: 제 생각에는, 왜냐하면, 동의하다, 반대하다."),
   ("‘___다고 생각해요, 왜냐하면 ___’", "I Think ___ Because ___",
    "주장과 근거를 함께 말하는 ‘저는 ___다고 생각해요, 왜냐하면 ___’ 문형을 배워요.",
    "State a claim with a reason: 저는 ___다고 생각해요, 왜냐하면 ___."),
   ("짧은 토론 듣기", "Listening: Mini Debate",
    "한 주제에 찬반 의견이 오가는 짧은 토론을 듣고 양쪽 근거를 잡아요.",
    "Hear a short pro/con debate and catch each side's reasons."),
   ("의견 말하기·설득 역할극", "Opinion & Persuasion Roleplay",
    "한 주제를 정해 근거를 들어 의견을 말하고 설득하는 역할극을 해요.",
    "Pick a topic and roleplay arguing your opinion with reasons."),
   ("찬반 토론 게임", "Pro/Con Debate Game",
    "찬성·반대 팀으로 나눠 근거를 모으는 게임으로 복습해요.",
    "Split into pro/con teams and gather reasons — a debate game."),
 ],
 20: [  # 돌발상황
   ("응급 어휘: 아프다·잃어버리다", "Emergency Words",
    "‘아프다·다치다·잃어버리다·약국·119·112’ 등 위급 상황 어휘를 익혀요.",
    "Emergency words: 아프다, 다치다, 잃어버리다, 약국, 119, 112."),
   ("‘___을 잃어버렸어요 / 도와주세요’", "I Lost ___ / Please Help",
    "‘지갑을 잃어버렸어요·도와주세요’처럼 도움을 청하는 문형을 배워요.",
    "Ask for help: 지갑을 잃어버렸어요, 도와주세요."),
   ("긴급 상황 통화 듣기", "Listening: Emergency Call",
    "신고·문의 통화를 듣고 무슨 일이 있었는지 핵심을 파악해요.",
    "Hear an emergency call and grasp what happened."),
   ("도움 요청 역할극", "Asking for Help Roleplay",
    "병원·약국·분실 상황에서 도움을 요청하는 역할극을 해요.",
    "Roleplay asking for help at a clinic, pharmacy, or lost-item desk."),
   ("상황별 대처 퀴즈", "Emergency Response Quiz",
    "상황 카드를 보고 알맞은 대처와 번호를 고르는 퀴즈로 복습해요.",
    "Pick the right response and number for each situation — a quiz."),
 ],
 21: [  # 인물묘사
   ("외모·성격 어휘", "Looks & Personality Words",
    "‘키·머리·친절하다·활발하다·조용하다’ 등 외모·성격 어휘를 익혀요.",
    "Appearance and personality: 키, 머리, 친절하다, 활발하다, 조용하다."),
   ("‘___은/는 ___고, ___아요’ 묘사 잇기", "Describing People (-고)",
    "‘그분은 키가 크고 친절해요’처럼 외모와 성격을 이어 묘사하는 문형을 배워요.",
    "Describe looks + personality: 그분은 키가 크고 친절해요."),
   ("인물 묘사 듣고 그리기", "Listening: Describe & Draw",
    "인물 묘사를 듣고 특징에 맞게 그려 보는 연습을 해요.",
    "Hear a description and sketch the person's features."),
   ("친구 소개·묘사 역할극", "Introduce a Friend Roleplay",
    "친구의 외모와 성격을 소개하고 묘사하는 역할극을 해요.",
    "Roleplay introducing a friend's looks and personality."),
   ("인물 맞히기 게임", "Guess-Who Game",
    "묘사를 듣고 여러 인물 중 누구인지 맞히는 게임으로 복습해요.",
    "Guess who from a description — a review game."),
 ],
 22: [  # 여행·계획
   ("여행 어휘: 예약·명소·숙소", "Travel Words",
    "‘여행·계획·예약·명소·숙소’ 등 여행에 필요한 어휘를 익혀요.",
    "Travel words: 여행, 계획, 예약, 명소, 숙소."),
   ("‘___에 가 본 적이 있어요 / ___ㄹ 계획이에요’", "Have Been / Plan To",
    "경험 ‘가 본 적이 있어요’와 계획 ‘갈 계획이에요’ 두 문형을 배워요.",
    "Experience (가 본 적이 있어요) and plans (갈 계획이에요)."),
   ("여행 후기 듣기", "Listening: Travel Story",
    "여행 다녀온 이야기를 듣고 어디를 가서 무엇을 했는지 파악해요.",
    "Hear a travel story and catch where they went and did."),
   ("여행 계획 세우기 역할극", "Trip-Planning Roleplay",
    "함께 갈 곳과 일정을 정하는 여행 계획 역할극을 해요.",
    "Roleplay planning a trip together — places and schedule."),
   ("여행 경험 말판 게임", "Travel Board Game",
    "칸마다 경험·계획을 말하며 도착하는 말판 게임으로 복습해요.",
    "Move across a board, telling experiences and plans — a review game."),
 ],
 23: [  # 모임·약속
   ("약속 어휘: 모임·회식·장소", "Appointment Words",
    "‘약속·모임·회식·장소·시간 정하다’ 등 약속 잡기 어휘를 익혀요.",
    "Planning words: 약속, 모임, 회식, 장소, 시간 정하다."),
   ("‘우리 같이 ___을래요? / ___에서 만나요’", "Shall We? / Let's Meet At",
    "‘우리 같이 점심 먹을래요?·역에서 만나요’처럼 제안·약속 문형을 배워요.",
    "Suggest and set plans: 같이 점심 먹을래요? 역에서 만나요."),
   ("약속 정하는 대화 듣기", "Listening: Making Plans",
    "두 사람이 시간·장소를 맞추는 대화를 듣고 약속 내용을 정리해요.",
    "Hear two people set a time and place, and note the plan."),
   ("약속 조율 역할극", "Scheduling Roleplay",
    "서로 가능한 시간을 맞춰 모임 약속을 정하는 역할극을 해요.",
    "Roleplay coordinating times to set up a meetup."),
   ("약속 잡기 게임", "Plan-It Game",
    "조건에 맞는 시간·장소를 찾아 약속을 완성하는 게임으로 복습해요.",
    "Find a time and place that fits — a planning review game."),
 ],
 24: [  # 마무리·수료
   ("핵심 어휘 총정리", "Vocabulary Wrap-Up",
    "24주 동안 배운 주제별 핵심 어휘를 한자리에 모아 정리해요.",
    "Gather and review the key vocabulary from all 24 weeks."),
   ("핵심 문형 총정리", "Pattern Wrap-Up",
    "‘이에요/예요·있어요·-고 싶어요·-다고 생각해요’ 등 핵심 문형을 총정리해요.",
    "Review the core patterns: 이에요/예요, 있어요, -고 싶어요, -다고 생각해요."),
   ("종합 듣기 진단", "Comprehensive Listening Check",
    "여러 주제가 섞인 종합 듣기로 그동안의 듣기 실력을 점검해요.",
    "A mixed-topic listening test to check your overall progress."),
   ("한국어로 내 이야기 발표", "Tell Your Story in Korean",
    "배운 표현으로 나를 소개하고 내 이야기를 한국어로 발표해요.",
    "Use everything you've learned to present your own story in Korean."),
   ("24주 종합 퀴즈 & 수료", "24-Week Final Quiz & Graduation",
    "전 과정을 아우르는 종합 퀴즈를 풀고 24주 여정을 수료해요.",
    "Take the all-course final quiz and graduate the 24-week journey."),
 ],
}

# DETAIL 인덱스 순서: Day2..Day5, Day7  →  슬롯 vocab/pattern/listen/speak/review
DAY_TO_DIDX = {2: 0, 3: 1, 4: 2, 5: 3, 7: 4}


def main():
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    weeks = {r["week"]: r for r in con.execute(
        "SELECT level,week,title_ko,title_en,target_letters FROM hangeul_curriculum ORDER BY week")}
    lessons = []
    for wk in range(1, 25):
        wrow = weeks[wk]
        lvl = wrow["level"]
        s_ko, s_en, c_title_ko, c_title_en, c_desc_ko, c_desc_en = W[wk]
        for day in range(1, 8):
            icon, sk_ko, sk_en = SLOT[day - 1]
            no = (wk - 1) * 7 + day
            anchor = (day == 1)
            if anchor:
                # Day1 = 기존 24강 핵심 영상(앵커). 기존 영상이 다루는 핵심.
                t_ko = f"{wrow['title_ko']}"
                t_en = f"{wrow['title_en']}"
                d_ko = "이번 주 핵심을 다루는 기존 핵심 영상 강의예요. 여기서 시작해요."
                d_en = "The week's core, taught in the main video lesson. Start here."
            elif day == 6:
                # Day6 = 문화 (주차별 구체)
                t_ko, t_en = c_title_ko, c_title_en
                d_ko, d_en = c_desc_ko, c_desc_en
            else:
                t_ko, t_en, d_ko, d_en = D[wk][DAY_TO_DIDX[day]]
            lessons.append({
                "no": no, "week": wk, "day": day, "level": lvl, "level_ko": LEVEL_KO[lvl],
                "theme_ko": wrow["title_ko"], "theme_en": wrow["title_en"],
                "skill": sk_en.lower().split()[0], "skill_ko": sk_ko, "skill_en": sk_en, "icon": icon,
                "title_ko": t_ko, "title_en": t_en,
                "desc_ko": d_ko, "desc_en": d_en,
                "target": wrow["target_letters"],
                "anchor": anchor, "is_new": not anchor,
                "video": f"hangeul_w{wk}_stickman" if anchor else None,
            })
    con.close()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    json.dump(lessons, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"{len(lessons)} lessons -> {os.path.relpath(OUT, ROOT)}")
    for lvl in ("beginner", "intermediate", "advanced"):
        n = sum(1 for x in lessons if x["level"] == lvl)
        print(f"  {LEVEL_KO[lvl]}: {n} lessons")
    # non-duplication sanity: distinct titles among non-anchor lessons
    titles = [x["title_ko"] for x in lessons if x["is_new"]]
    print(f"  new(non-anchor) lessons: {len(titles)}, distinct titles: {len(set(titles))}")


if __name__ == "__main__":
    main()
