import os
import glob
import re

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_FILE = os.path.join(ROOT_DIR, "autovideo_outputs.md")

# Gather all mp4 files
mp4_files = glob.glob(os.path.join(ROOT_DIR, "**", "*.mp4"), recursive=True)

# Filter out node_modules, .git, etc.
filtered_files = []
for f in mp4_files:
    if "node_modules" in f or ".git" in f or ".gemini" in f or "assets" in f:
        continue
    # Skip temporary files generated by MoviePy
    if "TEMP_MPY" in f:
        continue
    filtered_files.append(f)

def format_size(size_bytes):
    if size_bytes < 1024:
        return f"{size_bytes} B"
    elif size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.2f} KB"
    else:
        return f"{size_bytes / (1024 * 1024):.2f} MB"

def get_project_name(path, rel_path):
    parts = rel_path.replace("\\", "/").split("/")
    if len(parts) > 1:
        return parts[0]
    return "Root / Workspace"

catalog = []

for path in filtered_files:
    rel_path = os.path.relpath(path, ROOT_DIR)
    abs_path = os.path.abspath(path)
    size = os.path.getsize(path)
    filename = os.path.basename(path)
    
    project = get_project_name(path, rel_path)
    
    # Classify the type of video
    v_type = "Scene Video Clip (개별 씬 클립)"
    if filename.startswith("scene_"):
        v_type = "Scene Video Clip (개별 씬 클립)"
    elif filename == f"{project}.mp4" or filename == "output.mp4" or "final" in filename or "cloned" in filename:
        v_type = "Final Compiled Video (최종 합본 비디오)"
    else:
        v_type = "Scene Video Clip (개별 씬 클립)"
        
    catalog.append({
        "project": project,
        "filename": filename,
        "path": rel_path,
        "abs_path": abs_path,
        "size": size,
        "type": v_type
    })

# Group by Project, then by Type
projects = {}
for item in catalog:
    proj = item["project"]
    if proj not in projects:
        projects[proj] = {}
    v_type = item["type"]
    if v_type not in projects[proj]:
        projects[proj][v_type] = []
    projects[proj][v_type].append(item)

# Build Markdown
md = []
md.append("# AutoVideo Output & Clips Specification")
md.append("\n> **오토비디오 프로젝트 내 최종 렌더링 합본 비디오 및 생성된 개별 씬(Scene) 동영상 클립 목록**")
md.append("> ")
md.append("> *본 명세서는 조감독(Gemini)이 작성하여 감독(Claude)에게 전달하는 자료입니다.*")
md.append("> *새 영상 컴파일 및 분석 리팩토링 시 기제작된 비디오 결과물들과 씬 소스 클립들을 참고해 주십시오.*")
md.append("\n---\n")

for proj, types in sorted(projects.items()):
    md.append(f"## 프로젝트: `{proj}`")
    md.append("")
    
    for v_type, items in sorted(types.items()):
        md.append(f"### {v_type}")
        md.append("")
        md.append("| 파일명 (Filename) | 파일 절대 경로 (Absolute File Path) | 파일 크기 (Size) | 상태 및 설명 (Description) |")
        md.append("| :--- | :--- | :--- | :--- |")
        
        # Sort items safely
        def sort_key(x):
            match = re.search(r'scene_(\d+)', x["filename"])
            if match:
                return (0, int(match.group(1)))
            return (1, x["filename"])
            
        sorted_items = sorted(items, key=sort_key)
        
        for item in sorted_items:
            clean_abs_path = item['abs_path'].replace('\\', '/')
            if not clean_abs_path.startswith('/'):
                clean_abs_path = '/' + clean_abs_path
            path_link = f"[{item['filename']}](file://{clean_abs_path})"
            size_str = format_size(item['size'])
            
            desc = ""
            if "Final" in item['type']:
                desc = "MoviePy를 사용하여 합본 렌더링된 최종 4K/1080p 가이드 비디오"
            else:
                desc = "Google Flow(Veo)에서 생성 및 다운로드된 원본 비디오 클립"
                
            md.append(f"| `{item['filename']}` | {path_link} | {size_str} | {desc} |")
        md.append("")
        
    md.append("\n---\n")

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(md))

print(f"Video catalog successfully written to {OUTPUT_FILE}")
