import os
import json
import psycopg2
from supabase import create_client, Client

def load_keys():
    # Load .env variables manually
    env_vars = {}
    env_path = "D:/Entertainments/DevEnvironment/autovideo/.env"
    if os.path.exists(env_path):
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip() and not line.startswith("#"):
                    parts = line.strip().split("=", 1)
                    if len(parts) == 2:
                        env_vars[parts[0].strip()] = parts[1].strip()

    # Load service role key
    service_role_key = None
    keys_path = "scratch/supabase_keys_full.txt"
    if os.path.exists(keys_path):
        with open(keys_path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                if line.startswith("service_role="):
                    service_role_key = line.split("=", 1)[1].strip()
                    break

    return env_vars, service_role_key

def main():
    env_vars, service_role_key = load_keys()
    if not service_role_key:
        print("[ERR] service_role key not found!")
        return

    # Supabase Client setup
    url = "https://dggxjxgnsecspiubaeie.supabase.co"
    print(f"Connecting Supabase Client to {url}...")
    supabase: Client = create_client(url, service_role_key)

    # 1. Create Storage Bucket 'character-base'
    try:
        buckets = supabase.storage.list_buckets()
        bucket_names = [b.name for b in buckets]
        if "character-base" not in bucket_names:
            supabase.storage.create_bucket("character-base", options={"public": True})
            print("Successfully created bucket 'character-base'.")
        else:
            print("Bucket 'character-base' already exists.")
    except Exception as e:
        print(f"Error checking/creating storage bucket: {e}")
        # Fallback to postgres storage bucket creation if needed

    # 2. Connect to Supabase Postgres to create tables
    try:
        conn = psycopg2.connect(
            host="aws-1-ap-northeast-2.pooler.supabase.com",
            port=5432,
            user="postgres.dggxjxgnsecspiubaeie",
            password="sRlfjrl77!!",
            database="postgres"
        )
        cur = conn.cursor()
        
        # Create characters table
        cur.execute("""
            CREATE TABLE IF NOT EXISTS characters (
                id          TEXT PRIMARY KEY,
                name_kr     TEXT NOT NULL,
                name_en     TEXT NOT NULL,
                gender      TEXT,
                identity    TEXT,
                style       TEXT,
                tags        TEXT[],
                created_at  TIMESTAMPTZ DEFAULT NOW()
            );
        """)
        
        # Create character_assets table
        cur.execute("""
            CREATE TABLE IF NOT EXISTS character_assets (
                id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key          TEXT UNIQUE NOT NULL,
                character_id TEXT REFERENCES characters(id) ON DELETE CASCADE,
                view         TEXT NOT NULL, -- 'front', 'side', 'back'
                pose         TEXT NOT NULL, -- 'standing', 'sitting', etc.
                file_path    TEXT NOT NULL,
                storage_url  TEXT NOT NULL,
                method       TEXT NOT NULL, -- 'text2img', 'reference2img'
                style        TEXT,
                tags         TEXT[],
                method_doc   TEXT,
                created_at   TIMESTAMPTZ DEFAULT NOW()
            );
        """)
        
        # Create composite index
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_character_assets_id_view 
            ON character_assets(character_id, view);
        """)
        conn.commit()
        print("Database tables & indexes verified/created.")
    except Exception as e:
        print(f"[ERR] Postgres initialization failed: {e}")
        return

    # 3. Read Manifest
    manifest_path = "D:/Entertainments/DevEnvironment/autovideo/home_vocab/character_base_manifest.json"
    if not os.path.exists(manifest_path):
        print(f"[ERR] Manifest file not found at {manifest_path}")
        return

    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    global_tags = manifest.get("tags", [])
    method_doc = manifest.get("method_doc", "CHARACTER_ASSET_METHOD.md")

    uploaded_assets = []

    # 4. Upload and Register
    for char in manifest.get("characters", []):
        char_id = char.get("id")
        name_kr = char.get("name_kr")
        name_en = char.get("name_en")
        gender = char.get("gender")
        identity = char.get("identity")
        style = char.get("style")
        
        # Character tags: union of global tags and specific character info
        char_tags = list(set(global_tags + [char_id, gender]))

        print(f"\nProcessing character: {name_kr} ({char_id})...")
        
        # Insert Character
        cur.execute("""
            INSERT INTO characters (id, name_kr, name_en, gender, identity, style, tags)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (id) DO UPDATE SET
                name_kr = EXCLUDED.name_kr,
                name_en = EXCLUDED.name_en,
                gender = EXCLUDED.gender,
                identity = EXCLUDED.identity,
                style = EXCLUDED.style,
                tags = EXCLUDED.tags;
        """, (char_id, name_kr, name_en, gender, identity, style, char_tags))
        conn.commit()
        print(f"  Character record upserted in 'characters' table.")

        for photo in char.get("base_photos", []):
            photo_key = photo.get("key")
            view = photo.get("view")
            local_file = photo.get("file")
            method = photo.get("method")
            pose = "standing"  # standard base photos are standing

            full_local_path = os.path.join("D:/Entertainments/DevEnvironment/autovideo", local_file)
            if not os.path.exists(full_local_path):
                print(f"  [WARN] Local file {local_file} not found, skipping!")
                continue

            # Upload to Storage
            bucket_filename = os.path.basename(local_file)
            print(f"  Uploading {local_file} as {bucket_filename} to bucket 'character-base'...")
            
            storage_url = f"{url}/storage/v1/object/public/character-base/{bucket_filename}"
            
            try:
                # Remove if exists to allow clean overwrite/upsert
                try:
                    supabase.storage.from_("character-base").remove([bucket_filename])
                except Exception:
                    pass

                with open(full_local_path, "rb") as img_file:
                    supabase.storage.from_("character-base").upload(
                        path=bucket_filename,
                        file=img_file.read(),
                        file_options={"content-type": "image/png"}
                    )
                print(f"    Uploaded successfully. URL: {storage_url}")
            except Exception as upload_err:
                print(f"    [ERR] Upload failed: {upload_err}")
                # We can construct the URL anyway if we assume it exists
                # but we prefer successful uploads

            # Insert Character Asset
            asset_tags = list(set(char_tags + [view, pose, photo_key]))
            
            cur.execute("""
                INSERT INTO character_assets (key, character_id, view, pose, file_path, storage_url, method, style, tags, method_doc)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (key) DO UPDATE SET
                    character_id = EXCLUDED.character_id,
                    view = EXCLUDED.view,
                    pose = EXCLUDED.pose,
                    file_path = EXCLUDED.file_path,
                    storage_url = EXCLUDED.storage_url,
                    method = EXCLUDED.method,
                    style = EXCLUDED.style,
                    tags = EXCLUDED.tags,
                    method_doc = EXCLUDED.method_doc;
            """, (photo_key, char_id, view, pose, local_file, storage_url, method, style, asset_tags, method_doc))
            conn.commit()
            print(f"    Asset record upserted in 'character_assets' table.")
            uploaded_assets.append({
                "key": photo_key,
                "url": storage_url
            })

    cur.close()
    conn.close()
    print("\nAll database updates completed successfully!")
    print(f"Total assets processed: {len(uploaded_assets)}")
    for item in uploaded_assets:
        print(f" - {item['key']}: {item['url']}")

if __name__ == "__main__":
    main()
