# -*- coding: utf-8 -*-
"""
지은 동작 사진(점프·걷기) + 제작기법('이미지재생성')을 DB에 저장.
- Supabase: character-base 버킷 업로드 + character_assets upsert + techniques upsert
- 로컬 content.db 미러: assets upsert + techniques upsert
- 자격증명은 .env 에서만 로드. 멱등.

사용: python scratch/save_poses_all.py
"""
import os
import sys
import sqlite3

import psycopg2

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUCKET = "character-base"
METHOD_DOC = "POSE_GENERATION_METHOD.md"
STYLE = ("minimalist 2D line art, thick clean black outlines, whiteboard marker style, "
         "light beige background (#F5F5F0)")
TECH_NAME = "이미지재생성"

POSES = [
    {"key": "jieun_jumping", "kr": "지은_점프", "view": "front", "pose": "jumping",
     "file": "home_vocab/jieun_jumping.png", "ref": "jieun_base_front",
     "prompt": ("doing an energetic STAR JUMP high in mid-air: both arms stretched out wide, "
                "both legs spread wide apart, both feet off the ground, dynamic symmetric "
                "star-shaped jumping pose, front view")},
    {"key": "jieun_walking", "kr": "지은_걷기", "view": "side", "pose": "walking",
     "file": "home_vocab/jieun_walking.png", "ref": "jieun_base_side",
     "prompt": ("walking toward the LEFT in a clear left side profile view, mid-stride with one "
                "foot forward, EXACTLY ONE single girl, NOT a walking sequence, no duplicate figure")},
]

TECH_DESC = ("DB의 캐릭터 베이스 사진을 레퍼런스로 같은 캐릭터의 새 동작 사진을 Google Flow로 생성하는 기법. "
             "순서: 새 프로젝트→베이스 사진 업로드→(~25초)타일 더보기(⋮)→'프롬프트에 추가'(입력창 삽입)→"
             "동작 스크립트 입력→ENTER→(~45초)→왼편 '새' 타일만 다운로드(md5 중복검증). "
             "측면 동작은 'EXACTLY ONE single figure' 강제. 크롬 프로필은 한 번에 하나씩 순차 실행.")
TECH_TEMPLATE = ('python scratch/flow_pose.py --ref-key <base_key> --out-key <pose_key> '
                 '--prompt "<action phrase in English>"')


def load_env(p=None):
    p = p or os.path.join(ROOT, ".env")
    d = {}
    for ln in open(p, encoding="utf-8"):
        ln = ln.strip()
        if ln and not ln.startswith("#") and "=" in ln:
            k, v = ln.split("=", 1)
            d[k.strip()] = v.strip().strip('"').strip("'")
    return d


def save_supabase(env):
    url = env["SUPABASE_URL"]
    conn = psycopg2.connect(
        host=env["SUPABASE_DB_HOST"], port=env.get("SUPABASE_DB_PORT", "5432"),
        user=env["SUPABASE_DB_USER"], password=env["SUPABASE_DB_PASSWORD"],
        dbname=env.get("SUPABASE_DB_NAME", "postgres"), sslmode="require", connect_timeout=20)
    cur = conn.cursor()
    # techniques 테이블(없으면 생성)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS techniques (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT UNIQUE NOT NULL, description TEXT, reference_url TEXT,
            python_template TEXT, created_at TIMESTAMPTZ DEFAULT NOW());""")
    conn.commit()

    from supabase import create_client
    sb = create_client(url, env["SUPABASE_KEY"])

    for p in POSES:
        local = os.path.join(ROOT, p["file"])
        base = os.path.basename(p["file"])
        public = f"{url}/storage/v1/object/public/{BUCKET}/{base}"
        try:
            try:
                sb.storage.from_(BUCKET).remove([base])
            except Exception:
                pass
            with open(local, "rb") as fh:
                sb.storage.from_(BUCKET).upload(
                    path=base, file=fh.read(),
                    file_options={"content-type": "image/png", "upsert": "true"})
            print(f"  [storage] {base}")
        except Exception as ex:
            print(f"  [ERR] upload {base}: {ex}")
        tags = sorted({"jieun", "female", "pose", "이미지재생성", p["view"], p["pose"], p["key"]})
        cur.execute("""
            INSERT INTO character_assets
              (key,character_id,view,pose,file_path,storage_url,method,style,tags,method_doc)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            ON CONFLICT (key) DO UPDATE SET character_id=EXCLUDED.character_id,view=EXCLUDED.view,
              pose=EXCLUDED.pose,file_path=EXCLUDED.file_path,storage_url=EXCLUDED.storage_url,
              method=EXCLUDED.method,style=EXCLUDED.style,tags=EXCLUDED.tags,method_doc=EXCLUDED.method_doc;
        """, (p["key"], "jieun", p["view"], p["pose"], p["file"], public,
              "reference2img", STYLE, tags, METHOD_DOC))
        conn.commit()
        print(f"  [character_assets] {p['key']} ({p['pose']}/{p['view']})")

    cur.execute("""
        INSERT INTO techniques (name, description, reference_url, python_template)
        VALUES (%s,%s,%s,%s)
        ON CONFLICT (name) DO UPDATE SET description=EXCLUDED.description,
          reference_url=EXCLUDED.reference_url, python_template=EXCLUDED.python_template;
    """, (TECH_NAME, TECH_DESC, METHOD_DOC, TECH_TEMPLATE))
    conn.commit()
    print(f"  [techniques] {TECH_NAME}")
    cur.close()
    conn.close()


def save_local():
    db = os.path.join(ROOT, "channel", "content.db")
    conn = sqlite3.connect(db)
    cur = conn.cursor()
    names = [p["key"] for p in POSES]
    cur.execute(f"DELETE FROM assets WHERE name_en IN ({','.join('?' * len(names))})", names)
    cur.executemany(
        "INSERT INTO assets(name_kr,name_en,type,file_path,flow_prompt) VALUES (?,?,?,?,?)",
        [(p["kr"], p["key"], "character", os.path.basename(p["file"]), p["prompt"]) for p in POSES])
    cur.execute("""
        INSERT INTO techniques(name,description,reference_url,python_template)
        VALUES (?,?,?,?)
        ON CONFLICT(name) DO UPDATE SET description=excluded.description,
          reference_url=excluded.reference_url, python_template=excluded.python_template;
    """, (TECH_NAME, TECH_DESC, METHOD_DOC, TECH_TEMPLATE))
    conn.commit()
    na = cur.execute("SELECT COUNT(*) FROM assets").fetchone()[0]
    nt = cur.execute("SELECT COUNT(*) FROM techniques").fetchone()[0]
    conn.close()
    print(f"  [local assets] +{len(POSES)} (총 {na})  [local techniques] (총 {nt})")


def main():
    for p in POSES:
        if not os.path.exists(os.path.join(ROOT, p["file"])):
            raise SystemExit(f"[FAIL] 파일 없음: {p['file']}")
    env = load_env()
    print("== Supabase ==")
    save_supabase(env)
    print("== 로컬 content.db 미러 ==")
    save_local()
    print(f"\n[OK] 점프·걷기 2장 + 기법 '{TECH_NAME}' 저장 완료 (Supabase + 로컬)")


if __name__ == "__main__":
    main()
