-- 1. pgvector 확장 활성화
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. categories 테이블
CREATE TABLE IF NOT EXISTS categories (
    code         TEXT PRIMARY KEY,
    name_kr      TEXT NOT NULL,
    name_en      TEXT NOT NULL,
    medical_lens TEXT,
    priority     INTEGER DEFAULT 2
);

-- 3. episodes 테이블
CREATE TABLE IF NOT EXISTS episodes (
    code            TEXT PRIMARY KEY,
    category        TEXT NOT NULL REFERENCES categories(code) ON DELETE CASCADE,
    title_kr        TEXT NOT NULL,
    title_en        TEXT NOT NULL,
    hook_kr         TEXT,
    logline_kr      TEXT,
    status          TEXT DEFAULT 'idea',
    priority        INTEGER DEFAULT 2,
    target_chars_kr INTEGER DEFAULT 1300,
    target_words_en INTEGER DEFAULT 850,
    runtime_sec     INTEGER,
    narration_kr    TEXT,
    narration_en    TEXT,
    render_kr       TEXT,
    render_en       TEXT,
    youtube_kr      TEXT,
    youtube_en      TEXT,
    publish_date    TEXT,
    views           INTEGER DEFAULT 0,
    reverse_spec    TEXT,
    style_profile   TEXT,
    notes           TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 4. scenes 테이블
CREATE TABLE IF NOT EXISTS scenes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode      TEXT NOT NULL REFERENCES episodes(code) ON DELETE CASCADE,
    seq          INTEGER NOT NULL,
    script_kr    TEXT,
    script_en    TEXT,
    image_prompt TEXT,
    veo_prompt   TEXT,
    sfx          TEXT,
    duration_sec REAL,
    UNIQUE(episode, seq)
);

-- 5. techniques 테이블
CREATE TABLE IF NOT EXISTS techniques (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT UNIQUE NOT NULL,
    description     TEXT,
    reference_url   TEXT,
    python_template TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 6. episode_techniques 매핑 테이블
CREATE TABLE IF NOT EXISTS episode_techniques (
    episode_code TEXT REFERENCES episodes(code) ON DELETE CASCADE,
    technique_id BIGINT REFERENCES techniques(id) ON DELETE CASCADE,
    PRIMARY KEY (episode_code, technique_id)
);

-- 7. assets 테이블 (공용 에셋 라이브러리, 384차원 벡터 포함)
CREATE TABLE IF NOT EXISTS assets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_kr     TEXT NOT NULL,
    name_en     TEXT NOT NULL,
    type        TEXT NOT NULL, -- 'character', 'object', 'animal', 'bgm', 'sfx', 'background'
    file_path   TEXT,
    flow_prompt TEXT,
    embedding   vector(384),   -- sentence-transformers(all-MiniLM-L6-v2) 용 384차원 벡터
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 8. scene_objects 테이블 (씬별 레이어 배치)
CREATE TABLE IF NOT EXISTS scene_objects (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode    TEXT NOT NULL,
    scene_seq  INTEGER NOT NULL,
    asset_id   BIGINT REFERENCES assets(id) ON DELETE SET NULL,
    cx         INTEGER NOT NULL,
    cy         INTEGER NOT NULL,
    scale      REAL DEFAULT 1.0,
    z_order    INTEGER DEFAULT 3,
    is_point   BOOLEAN DEFAULT FALSE,
    motion_type TEXT,
    FOREIGN KEY(episode, scene_seq) REFERENCES scenes(episode, seq) ON DELETE CASCADE
);

-- 9. scene_transitions 테이블 (씬간 프레임 계승)
CREATE TABLE IF NOT EXISTS scene_transitions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode             TEXT NOT NULL REFERENCES episodes(code) ON DELETE CASCADE,
    from_scene_seq      INTEGER NOT NULL,
    to_scene_seq        INTEGER NOT NULL,
    transition_type     TEXT NOT NULL, -- 'last_frame_transition' 등
    exported_frame_path TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 10. web_lessons 테이블 (TED-Ed 퀴즈 연동)
CREATE TABLE IF NOT EXISTS web_lessons (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_code   TEXT UNIQUE NOT NULL REFERENCES episodes(code) ON DELETE CASCADE,
    quiz_question  TEXT,
    quiz_options   TEXT, -- 선택지 (JSON 구조 등)
    quiz_answer    TEXT,
    dig_deeper_doc TEXT
);

-- 11. channel_meta 테이블
CREATE TABLE IF NOT EXISTS channel_meta (
    key   TEXT PRIMARY KEY,
    value TEXT
);

-- 12. 코사인 유사도 기반 에셋 검색 SQL 함수 (AI가 쉽게 호출할 수 있도록 제공)
CREATE OR REPLACE FUNCTION match_assets(
    query_embedding vector(384),
    match_threshold float,
    match_count int
)
RETURNS TABLE (
    id bigint,
    name_kr text,
    name_en text,
    type text,
    file_path text,
    flow_prompt text,
    similarity float
)
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
    SELECT
        a.id,
        a.name_kr,
        a.name_en,
        a.type,
        a.file_path,
        a.flow_prompt,
        1 - (a.embedding <=> query_embedding) AS similarity
    FROM assets a
    WHERE 1 - (a.embedding <=> query_embedding) > match_threshold
    ORDER BY a.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;
